//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIME {
    
    
    public partial class Contas {
        
        /// <summary>
        /// Labteste control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Labteste;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SIME.SiteMaster Master {
            get {
                return ((SIME.SiteMaster)(base.Master));
            }
        }
    }
}
