//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIME {
    
    
    public partial class logar {
        
        /// <summary>
        /// ToolkitScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        /// <summary>
        /// dados1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.DropShadowExtender dados1;
        
        /// <summary>
        /// Panel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel3;
        
        /// <summary>
        /// Image1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image Image1;
        
        /// <summary>
        /// txtUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUser;
        
        /// <summary>
        /// laberrousuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label laberrousuario;
        
        /// <summary>
        /// TxtSenha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox TxtSenha;
        
        /// <summary>
        /// laberosenha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label laberosenha;
        
        /// <summary>
        /// Btlogar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Btlogar;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SIME.SiteMaster Master {
            get {
                return ((SIME.SiteMaster)(base.Master));
            }
        }
    }
}
