//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIME {
    
    
    public partial class producao {
        
        /// <summary>
        /// Panel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel Panel3;
        
        /// <summary>
        /// scriptMaster control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager scriptMaster;
        
        /// <summary>
        /// cobUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList cobUsuario;
        
        /// <summary>
        /// txtInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtInicio;
        
        /// <summary>
        /// txtInicio_CalendarExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender txtInicio_CalendarExtender;
        
        /// <summary>
        /// txtFim control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFim;
        
        /// <summary>
        /// txtFim_CalendarExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CalendarExtender txtFim_CalendarExtender;
        
        /// <summary>
        /// BtPesquisar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtPesquisar;
        
        /// <summary>
        /// labAtingido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labAtingido;
        
        /// <summary>
        /// Chart1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.DataVisualization.Charting.Chart Chart1;
        
        /// <summary>
        /// labResumo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labResumo;
        
        /// <summary>
        /// Panel3_CollapsiblePanelExtender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.CollapsiblePanelExtender Panel3_CollapsiblePanelExtender;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SIME.SiteMaster Master {
            get {
                return ((SIME.SiteMaster)(base.Master));
            }
        }
    }
}
