//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGENDA
    {
        public int CONTROLE { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAAGENDAMENTO { get; set; }
        public Nullable<System.TimeSpan> HORAAGENDAMENTO { get; set; }
        public string STATUS { get; set; }
        public string PRIORIDADE { get; set; }
        public string OBS { get; set; }
        public string TIPOAGENDAMENTO { get; set; }
        public string CELULAR { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CODUSUARIO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CONTATO { get; set; }
    }
}
