//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGENDAMENTOOS
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<System.DateTime> DATAAGENDAMENTO { get; set; }
        public Nullable<System.TimeSpan> HORAAGENDAMENTO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<int> CODOS { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public string STATUS { get; set; }
        public string CELULAR { get; set; }
        public string TELEFONE { get; set; }
        public string CONTATO { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CODOBJETO { get; set; }
        public string DESCRICAOOBJETO { get; set; }
    }
}
