//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAJUSTE
    {
        public TAJUSTE()
        {
            this.TITEMAJUSTE = new HashSet<TITEMAJUSTE>();
        }
    
        public int CONTROLE { get; set; }
        public string CODIGOAJUSTE { get; set; }
        public string DESCRICAOAJUSTE { get; set; }
        public Nullable<decimal> VALORAJUSTE { get; set; }
    
        public virtual ICollection<TITEMAJUSTE> TITEMAJUSTE { get; set; }
    }
}
