//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAJUSTEESTOQUE
    {
        public int CONTROLE { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public int CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public decimal QTDEANTERIOR { get; set; }
        public decimal QTDENOVA { get; set; }
        public decimal QTDEALTERADA { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
    
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
    }
}
