//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TALTERACAODAV
    {
        public int CONTROLE { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string TIPO { get; set; }
        public string NUMERODAV { get; set; }
        public System.DateTime DATAALTERACAO { get; set; }
        public System.TimeSpan HORAALTERACAO { get; set; }
        public string CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public decimal QTDE { get; set; }
        public string UN { get; set; }
        public decimal VALORUNITARIO { get; set; }
        public decimal VALORDESCONTOITEM { get; set; }
        public decimal VALORACRESCIMOITEM { get; set; }
        public decimal VALORTOTALLIQUIDO { get; set; }
        public string SITUACAOTRIBUTARIA { get; set; }
        public decimal ALIQUOTA { get; set; }
        public string INDICADORCANCELAMENTO { get; set; }
        public decimal DECIMAISQTDE { get; set; }
        public decimal DECIMAISVALORUNITARIO { get; set; }
        public string TIPOALTERACAO { get; set; }
        public string GRAVOU { get; set; }
        public Nullable<int> CODORCAMENTO { get; set; }
        public Nullable<int> CODITEMORCAMENTO { get; set; }
        public Nullable<int> CODPEDIDOVENDA { get; set; }
        public Nullable<int> CODITEMPEDIDOVENDA { get; set; }
        public Nullable<int> CODCONDICIONAL { get; set; }
        public Nullable<int> CODITEMCONDICIONAL { get; set; }
        public Nullable<int> CODOS { get; set; }
        public Nullable<int> CODITEMOS { get; set; }
        public string MD5 { get; set; }
    }
}
