//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOLETOAGRUPADO
    {
        public int CONTROLE { get; set; }
        public string NOSSONUMERO { get; set; }
        public string RECEBER { get; set; }
        public Nullable<int> CODBOLETO { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string DATAVENCIMENTONOVA { get; set; }
    }
}
