//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBOLETO
    {
        public int CONTROLE { get; set; }
        public string NOSSONUMERO { get; set; }
        public string BANCO { get; set; }
        public Nullable<System.DateTime> VENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATADOCUMENTO { get; set; }
        public Nullable<decimal> VALORDOCUMENTO { get; set; }
        public string ESPECIEDOCUMENTO { get; set; }
        public string ACEITE { get; set; }
        public Nullable<System.DateTime> DATAPROCESSAMENTO { get; set; }
        public Nullable<decimal> VALORABATIMENTO { get; set; }
        public Nullable<decimal> VALORMORAJUROS { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public string DATADESCONTO { get; set; }
        public string DATAMORAJUROS { get; set; }
        public Nullable<System.DateTime> DATAPROTESTO { get; set; }
        public string CARTEIRA { get; set; }
        public string LOCALPAGAMENTO { get; set; }
        public Nullable<decimal> PERCENTUALMULTA { get; set; }
        public string MENSAGEM { get; set; }
        public string NOMECEDENTE { get; set; }
        public string CPFCNPJCEDENTE { get; set; }
        public string ENDERECOCEDENTE { get; set; }
        public string NUMEROCEDENTE { get; set; }
        public string COMPLEMENTOCEDENTE { get; set; }
        public string BAIRROCEDENTE { get; set; }
        public string CIDADECEDENTE { get; set; }
        public string UFCEDENTE { get; set; }
        public string CEPCEDENTE { get; set; }
        public string TELEFONECEDENTE { get; set; }
        public string CODIGOCEDENTE { get; set; }
        public string MODALIDADECEDENTE { get; set; }
        public string CONVENIOCEDENTE { get; set; }
        public string AGENCIACEDENTE { get; set; }
        public string AGENCIADIGITOCEDENTE { get; set; }
        public string CONTACEDENTE { get; set; }
        public string CONTADIGITOCEDENTE { get; set; }
        public string NOMESACADO { get; set; }
        public string CNPJCPFSACADO { get; set; }
        public string ENDERECOSACADO { get; set; }
        public string NUMEROSACADO { get; set; }
        public string BAIRROSACADO { get; set; }
        public string CIDADESACADO { get; set; }
        public string UFSACADO { get; set; }
        public string CEPSACADO { get; set; }
        public string INSTRUCAO1 { get; set; }
        public string INSTRUCAO2 { get; set; }
        public string NUMERODOCUMENTO { get; set; }
        public string BOLETOCONFIRMADO { get; set; }
        public Nullable<int> CODBANCO { get; set; }
        public Nullable<int> CODRECEBER { get; set; }
        public string DATAABATIMENTO { get; set; }
        public string GEROUREMESSA { get; set; }
        public Nullable<int> NPARCELA { get; set; }
        public Nullable<int> QTDEPARCELA { get; set; }
        public string OCORRENCIAMOVIMENTO { get; set; }
        public string STATUS { get; set; }
        public string NOMEAVALISTA { get; set; }
        public string CNPJCPFAVALISTA { get; set; }
        public string ENDERECOAVALISTA { get; set; }
        public string NUMEROAVALISTA { get; set; }
        public string COMPLEMENTOAVALISTA { get; set; }
        public string BAIRROAVALISTA { get; set; }
        public string CIDADEAVALISTA { get; set; }
        public string CEPAVALISTA { get; set; }
        public string UFAVALISTA { get; set; }
        public string TELEFONEAVALISTA { get; set; }
        public string EMAILAVALISTA { get; set; }
        public Nullable<int> CODSACADO { get; set; }
        public Nullable<int> CODAVALISTA { get; set; }
        public Nullable<int> CODCEDENTE { get; set; }
    }
}
