//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCAIXA
    {
        public TCAIXA()
        {
            this.TFORMAPAGAMENTOALUGUEL = new HashSet<TFORMAPAGAMENTOALUGUEL>();
        }
    
        public int CONTROLE { get; set; }
        public string DESCRICAOLANCAMENTO { get; set; }
        public Nullable<int> CODCENTROCUSTO { get; set; }
        public string CENTROCUSTO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string ORIGEM { get; set; }
        public string DOCUMENTO { get; set; }
        public Nullable<decimal> VALORENTRADA { get; set; }
        public Nullable<decimal> VALORSAIDA { get; set; }
        public Nullable<decimal> SALDO { get; set; }
        public Nullable<int> CODPAGAR { get; set; }
        public Nullable<int> CODRECEBER { get; set; }
        public Nullable<int> CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public string OBS { get; set; }
        public Nullable<int> CODPLANCONTA { get; set; }
        public string PLANCONTA { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public Nullable<int> CODPDV { get; set; }
        public string COOCCFPDV { get; set; }
        public Nullable<int> CODOS { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CODCOMPRA { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public string FORNECEDOR { get; set; }
        public Nullable<int> CODNFE { get; set; }
        public Nullable<int> CODNFCE { get; set; }
        public Nullable<int> CODFUNCIONARIOVALE { get; set; }
        public string FUNCIONARIOVALE { get; set; }
        public Nullable<int> CODMODULO { get; set; }
    
        public virtual TCENTROCUSTO TCENTROCUSTO { get; set; }
        public virtual TPAGAR TPAGAR { get; set; }
        public virtual TRECEBER TRECEBER { get; set; }
        public virtual TESPECIE TESPECIE { get; set; }
        public virtual TPLANOCONTA TPLANOCONTA { get; set; }
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual TFORNECEDOR TFORNECEDOR { get; set; }
        public virtual ICollection<TFORMAPAGAMENTOALUGUEL> TFORMAPAGAMENTOALUGUEL { get; set; }
    }
}
