//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCCE
    {
        public int CONTROLE { get; set; }
        public string VERSAO { get; set; }
        public string IDLOTE { get; set; }
        public string VERAPLIC { get; set; }
        public string ORGAO { get; set; }
        public string CODIGOSTATUS { get; set; }
        public string MOTIVO { get; set; }
        public string CHAVEACESSO { get; set; }
        public string SEQUENCIAEVENTO { get; set; }
        public string CNPJDESTINATARIO { get; set; }
        public string CPFDESTINATARIO { get; set; }
        public string EMAILDESTINATARIO { get; set; }
        public string PROTOCOLO { get; set; }
        public Nullable<System.DateTime> DATAHORAEVENTO { get; set; }
        public string CODIGOTIPOEVENTO { get; set; }
        public string DESCRICAOEVENTO { get; set; }
        public Nullable<int> TIPOAMBIENTE { get; set; }
        public string AMBIENTE { get; set; }
        public string STATUS { get; set; }
    }
}
