//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCENTROCUSTO
    {
        public TCENTROCUSTO()
        {
            this.TCAIXA = new HashSet<TCAIXA>();
            this.TPAGAR = new HashSet<TPAGAR>();
            this.TRECEBER = new HashSet<TRECEBER>();
            this.TUSUARIO = new HashSet<TUSUARIO>();
            this.TVENDANFCE = new HashSet<TVENDANFCE>();
        }
    
        public int CONTROLE { get; set; }
        public string CENTROCUSTO { get; set; }
        public string OBS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
    
        public virtual ICollection<TCAIXA> TCAIXA { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
        public virtual ICollection<TRECEBER> TRECEBER { get; set; }
        public virtual ICollection<TUSUARIO> TUSUARIO { get; set; }
        public virtual ICollection<TVENDANFCE> TVENDANFCE { get; set; }
    }
}
