//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCFOP
    {
        public int CONTROLE { get; set; }
        public string DESCRICAOABREVIADA { get; set; }
        public string DESCRICAODETALHADA { get; set; }
        public string MOVIMENTOESTOQUE { get; set; }
        public string USACREDTIO { get; set; }
        public string CODIGOCFOP { get; set; }
        public string TIPOOPERACAO { get; set; }
    }
}
