//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCIDADEIBGE
    {
        public int CONTROLE { get; set; }
        public string CODIGOMUNICIPIO { get; set; }
        public string MUNICIPIO { get; set; }
        public string UF { get; set; }
    }
}
