//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCODIGOFABRICA
    {
        public int CONTROLE { get; set; }
        public string CODFABRICA { get; set; }
        public int CODFORNECEDOR { get; set; }
        public int CODPRODUTO { get; set; }
        public string DESCRICAOFORNECEDOR { get; set; }
        public string DESCRICAOPRODUTO { get; set; }
    
        public virtual TFORNECEDOR TFORNECEDOR { get; set; }
    }
}
