//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCOMPRA
    {
        public TCOMPRA()
        {
            this.TITEMCOMPRA = new HashSet<TITEMCOMPRA>();
            this.TITEMCOMPRAGRADE = new HashSet<TITEMCOMPRAGRADE>();
            this.TITEMCOMPRASERIAL = new HashSet<TITEMCOMPRASERIAL>();
            this.TITEMOPCOMPOSICAO = new HashSet<TITEMOPCOMPOSICAO>();
            this.TPAGAR = new HashSet<TPAGAR>();
        }
    
        public int CONTROLE { get; set; }
        public Nullable<int> NUMERONOTA { get; set; }
        public string NATUREZAOPERACAO { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string SUBSERIE { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<System.DateTime> DATARECEBIMENTO { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public string FORNECEDOR { get; set; }
        public Nullable<int> CODTRANSPORTADORA { get; set; }
        public string TRANSPORTADORA { get; set; }
        public Nullable<decimal> BASECALCICMS { get; set; }
        public Nullable<decimal> VALORICMS { get; set; }
        public Nullable<decimal> TOTALREDUCAOICMS { get; set; }
        public Nullable<decimal> BASECALCICMSST { get; set; }
        public Nullable<decimal> VALORICMSSUBSTITUICAO { get; set; }
        public Nullable<decimal> TOTALBCIPI { get; set; }
        public Nullable<decimal> VALORTOTALIPI { get; set; }
        public Nullable<decimal> TOTALPIS { get; set; }
        public Nullable<decimal> TOTALPISSUB { get; set; }
        public Nullable<decimal> TOTALCOFINS { get; set; }
        public Nullable<decimal> TOTALCOFINSSUB { get; set; }
        public Nullable<int> MODOFRETE { get; set; }
        public string TIPOFRETE { get; set; }
        public Nullable<decimal> VALORICMSFRETE { get; set; }
        public Nullable<decimal> VALORFRETE { get; set; }
        public Nullable<decimal> VALORSEGURO { get; set; }
        public Nullable<decimal> PERCDESCONTO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> OUTRASDESPESAS { get; set; }
        public Nullable<decimal> TOTALSERVICOS { get; set; }
        public Nullable<decimal> VALORTOTALPRODUTO { get; set; }
        public Nullable<decimal> VALORENTRADA { get; set; }
        public Nullable<decimal> VALORTOTALNOTA { get; set; }
        public string NFE { get; set; }
        public string PROTOCOLODANFE { get; set; }
        public string CHAVEACESSODANFE { get; set; }
        public string INFORMACOESCOMPLEMENTARES { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IESUBSTITUTOTRIBUTARIO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string TELEFONE { get; set; }
        public string EMAIL { get; set; }
        public string SITEFORNECEDOR { get; set; }
        public Nullable<System.TimeSpan> HORASAIDA { get; set; }
        public string CODIGOANTT { get; set; }
        public string PLACAVAICULO { get; set; }
        public string UFTRANSPORTADORA { get; set; }
        public string CNPJTRANSPORTADORA { get; set; }
        public string CPFTRANSPORTADORA { get; set; }
        public string ENDERECOTRANSPORTADORA { get; set; }
        public Nullable<int> CODCIDADETRANSPORTADORA { get; set; }
        public string CIDADETRANSPORTADORA { get; set; }
        public string BAIRROTRANSPORTADORA { get; set; }
        public string CEPTRANSPORTADORA { get; set; }
        public string IETRANSPORTADORA { get; set; }
        public Nullable<decimal> QTDEVOLUME { get; set; }
        public string ESPECIEVOLUME { get; set; }
        public string MARCAVOLUME { get; set; }
        public string NUMEROVOLUME { get; set; }
        public Nullable<decimal> PESOBRUTONOTA { get; set; }
        public Nullable<decimal> PESOLIQUIDONOTA { get; set; }
        public string OBS { get; set; }
        public string FORMAPAGAMENTO { get; set; }
        public Nullable<int> CODOPERACAO { get; set; }
        public Nullable<int> TIPOOPERACAO { get; set; }
        public string MOVIMENTAESTOQUE { get; set; }
        public string MOVIMENTAFINANCEIRO { get; set; }
        public string AVISTA { get; set; }
        public Nullable<decimal> TOTALBCIPPI { get; set; }
    
        public virtual TFORNECEDOR TFORNECEDOR { get; set; }
        public virtual TTRANSPORTADORA TTRANSPORTADORA { get; set; }
        public virtual ICollection<TITEMCOMPRA> TITEMCOMPRA { get; set; }
        public virtual ICollection<TITEMCOMPRAGRADE> TITEMCOMPRAGRADE { get; set; }
        public virtual ICollection<TITEMCOMPRASERIAL> TITEMCOMPRASERIAL { get; set; }
        public virtual ICollection<TITEMOPCOMPOSICAO> TITEMOPCOMPOSICAO { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
    }
}
