//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCOMANDA
    {
        public TCOMANDA()
        {
            this.TITEMCOMANDA = new HashSet<TITEMCOMANDA>();
        }
    
        public int CONTROLE { get; set; }
        public int NUMEROMESA { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATAABERTURA { get; set; }
        public Nullable<System.TimeSpan> HORAABERTURA { get; set; }
        public Nullable<System.DateTime> DATAFECHAMENTO { get; set; }
        public Nullable<System.TimeSpan> HORAFECHAMENTO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> VALORCOMISSAO { get; set; }
        public string SERIEECFCF { get; set; }
        public string COOCF { get; set; }
        public string SERIEECFRG { get; set; }
        public string COORG { get; set; }
        public Nullable<int> OCUPANTES { get; set; }
        public Nullable<decimal> VALOROCUPANTE { get; set; }
        public Nullable<decimal> VALORPRODUTOS { get; set; }
        public Nullable<int> CER { get; set; }
        public Nullable<int> NUMEROECFCONFERENCIAMESA { get; set; }
        public Nullable<int> COOCONFERENCIAMESA { get; set; }
        public Nullable<System.DateTime> DATAEHORAABERTURAORIGEM { get; set; }
        public Nullable<System.DateTime> DATAMOVIMENTO { get; set; }
        public string ENDERECO { get; set; }
        public string NUMERO { get; set; }
        public string BAIRRO { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string PEDIDO { get; set; }
        public string COMPLEMENTO { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string CODBARRAS { get; set; }
        public Nullable<decimal> PERCCOMISSAO { get; set; }
        public Nullable<decimal> TAXASERVICO { get; set; }
        public string OBS { get; set; }
        public Nullable<int> SENHACOMANDA { get; set; }
        public string MD5 { get; set; }
        public Nullable<int> CONTROLEBASEMOBILE { get; set; }
        public string IMEIMOBILE { get; set; }
    
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual ICollection<TITEMCOMANDA> TITEMCOMANDA { get; set; }
    }
}
