//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCONTABANCARIA
    {
        public TCONTABANCARIA()
        {
            this.TMOVBANCO = new HashSet<TMOVBANCO>();
        }
    
        public int CONTROLE { get; set; }
        public string NOMEBANCO { get; set; }
        public string AGENCIA { get; set; }
        public string CONTACORRENTE { get; set; }
        public Nullable<decimal> SALDOREAL { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string ENDERECO { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string GERENTECONTA { get; set; }
        public Nullable<decimal> LIMITE { get; set; }
        public string NUMEROBANCO { get; set; }
        public string DIGITONUMEROBANCO { get; set; }
        public string NOMEAGENCIA { get; set; }
        public string NUMEROAGENCIA { get; set; }
        public string DIGITOAGENCIA { get; set; }
        public string DIGITOCONTA { get; set; }
        public string MSGLOCALPAGAMENTO { get; set; }
        public string ACEITE { get; set; }
        public string NOSSONUMERO { get; set; }
        public string ESPECIEDCTO { get; set; }
        public string CARTEIRA { get; set; }
        public Nullable<decimal> JUROBOLETO { get; set; }
        public Nullable<decimal> MULTABOLETO { get; set; }
        public Nullable<int> DIASPARAPROTESTO { get; set; }
        public string MENSAGEMPADRAO { get; set; }
        public string INSTRUCAO1 { get; set; }
        public string INSTRUCAO2 { get; set; }
        public string BANCO { get; set; }
        public string LOGO { get; set; }
        public string CODIGOCEDENTE { get; set; }
        public string MODALIDADE { get; set; }
        public string CONVENIO { get; set; }
        public string LEIAUTE { get; set; }
        public string CNAB { get; set; }
        public Nullable<decimal> NOSSONUMEROSEQUENCIA { get; set; }
        public string TIPODESCONTO { get; set; }
        public string SEQUENCIAREMESSA { get; set; }
        public Nullable<int> NUMEROREMESSA { get; set; }
        public Nullable<int> DIASMORAJURO { get; set; }
        public string COMREGISTRO { get; set; }
        public string SALVAREMESSA { get; set; }
        public Nullable<int> TIPOSALVAREMESSA { get; set; }
        public string LAYOUTREMESSA { get; set; }
        public string LAYOUTRETORNO { get; set; }
        public string CODIGOCEDENTERETORNO { get; set; }
        public string MENSAGEMSACADORAVALISTA { get; set; }
    
        public virtual TCIDADE TCIDADE { get; set; }
        public virtual ICollection<TMOVBANCO> TMOVBANCO { get; set; }
    }
}
