//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCONTAGEMESTOQUE
    {
        public TCONTAGEMESTOQUE()
        {
            this.TITEMCONTAGEMESTOQUE = new HashSet<TITEMCONTAGEMESTOQUE>();
        }
    
        public int CONTROLE { get; set; }
        public string DESCRICAOCONTAGEM { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public System.TimeSpan HORACADASTRO { get; set; }
        public decimal VALORAJUSTADO { get; set; }
        public string TIPOCONTAGEM { get; set; }
        public int QTDEREGISTROS { get; set; }
        public string FINALIZADA { get; set; }
        public Nullable<System.DateTime> DATAFINALIZADA { get; set; }
    
        public virtual ICollection<TITEMCONTAGEMESTOQUE> TITEMCONTAGEMESTOQUE { get; set; }
    }
}
