//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCONFIGURACAO
    {
        public int CONTROLE { get; set; }
        public string OBSOS { get; set; }
        public string MENSAGEMFIXAOS { get; set; }
        public string OBSOP { get; set; }
        public string RECEBER { get; set; }
        public string PAGAR { get; set; }
        public string CAIXA { get; set; }
        public string BANCO { get; set; }
        public string NFE { get; set; }
        public string COMPRAS { get; set; }
        public string PDVABERTO { get; set; }
        public Nullable<System.DateTime> DATACALCULOJUROSRECEBER { get; set; }
        public Nullable<System.DateTime> DATACALCULOJUROSPAGAR { get; set; }
        public Nullable<System.DateTime> DATACALCULACAIXA { get; set; }
        public Nullable<System.DateTime> DATACALCULAMOVBANCO { get; set; }
        public string OBSALUGUEL { get; set; }
        public string CONTRATOALUGUEL { get; set; }
        public string OBSORCAMENTO { get; set; }
        public string CANHOTOORCAMENTO { get; set; }
    }
}
