//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCOTACAOFORNECEDOR
    {
        public int CONTROLE { get; set; }
        public string FORNECEDOR { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public Nullable<int> CODCOTACAO { get; set; }
        public string SELECIONADO { get; set; }
        public string MARCADO { get; set; }
        public Nullable<int> CODPEDIDOCOMPRA { get; set; }
    
        public virtual TCOTACAO TCOTACAO { get; set; }
    }
}
