//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCSTICMS
    {
        public int CONTROLE { get; set; }
        public int CODIGOCST { get; set; }
        public string DESCRICAO { get; set; }
        public string PERMITECREDITO { get; set; }
        public string POSSUIICMSST { get; set; }
        public string ISENTO { get; set; }
        public string TRIBUTADO { get; set; }
        public string OC { get; set; }
    }
}
