//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTEQTDECARGA
    {
        public int CONTROLE { get; set; }
        public string UNMEDIDA { get; set; }
        public string TIPOMEDIDA { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<int> CODCTE { get; set; }
    }
}
