//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTENFORIGINARIA
    {
        public int CONTROLE { get; set; }
        public string NUMERO { get; set; }
        public string SERIE { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<decimal> BCICMS { get; set; }
        public Nullable<decimal> TOTALICMS { get; set; }
        public Nullable<decimal> BCICMSST { get; set; }
        public Nullable<decimal> TOTALICMSST { get; set; }
        public Nullable<decimal> TOTALPRODUTOS { get; set; }
        public Nullable<decimal> TOTALNFE { get; set; }
        public Nullable<int> CFOP { get; set; }
        public Nullable<decimal> PESO { get; set; }
        public string PINSUFRAMA { get; set; }
        public Nullable<int> CODCTE { get; set; }
        public string NUMEROROMANEIO { get; set; }
        public string NUMEROPEDIDO { get; set; }
        public string MODELODOCUMENTO { get; set; }
    
        public virtual TCTE TCTE { get; set; }
    }
}
