//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTENFEORIGINARIA
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODCTE { get; set; }
        public string CHAVENFE { get; set; }
        public string PINSUFRAMA { get; set; }
        public Nullable<System.DateTime> DATAPREVISTAENTREGA { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
    
        public virtual TCTE TCTE { get; set; }
    }
}
