//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCTRC
    {
        public TCTRC()
        {
            this.TNOTACTRC = new HashSet<TNOTACTRC>();
            this.TPAGAR = new HashSet<TPAGAR>();
        }
    
        public int CONTROLE { get; set; }
        public string NUMEROCTRC { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string SUBSERIE { get; set; }
        public Nullable<int> CODOPERACAO { get; set; }
        public string NATUREZAOPERACAO { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<System.DateTime> DATAAQUISICAOPRESTACAO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CODFORNECTRANSP { get; set; }
        public string FORNECTRANSP { get; set; }
        public string CNPJ { get; set; }
        public string SITUACAO { get; set; }
        public string MODOFRETE { get; set; }
        public string CHAVECTE { get; set; }
        public string PROTOCOLO { get; set; }
        public string CFOP { get; set; }
        public string TIPOCTE { get; set; }
        public string CHAVECTEREFERENCIADO { get; set; }
        public string CST { get; set; }
        public Nullable<decimal> ALIQUOTAICMS { get; set; }
        public Nullable<decimal> BCICMS { get; set; }
        public Nullable<decimal> TOTALICMS { get; set; }
        public string CSTPIS { get; set; }
        public Nullable<decimal> ALIQUOTAPIS { get; set; }
        public Nullable<decimal> BCPIS { get; set; }
        public Nullable<decimal> TOTALPIS { get; set; }
        public string CSTCOFINS { get; set; }
        public Nullable<decimal> ALIQUOTACOFINS { get; set; }
        public Nullable<decimal> BCCOFINS { get; set; }
        public Nullable<decimal> TOTALCOFINS { get; set; }
        public Nullable<decimal> TOTALISENTO { get; set; }
        public Nullable<decimal> TOTALOUTROS { get; set; }
        public Nullable<decimal> TOTALSERVICO { get; set; }
        public Nullable<decimal> TOTALDESCONTO { get; set; }
        public string MOVIMENTAFINANCEIRO { get; set; }
        public string AVISTA { get; set; }
        public Nullable<decimal> VALORENTRADA { get; set; }
        public string TIPOPARTICIPANTE { get; set; }
        public Nullable<decimal> TOTALPRODUTO { get; set; }
        public Nullable<decimal> TOTALCTE { get; set; }
    
        public virtual TOPERACAO TOPERACAO { get; set; }
        public virtual ICollection<TNOTACTRC> TNOTACTRC { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
    }
}
