//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDAVD3
    {
        public int CONTROLE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string NUMERODAV { get; set; }
        public Nullable<System.DateTime> DATAINCLUSAO { get; set; }
        public Nullable<int> NUMEROITEM { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public Nullable<decimal> DESCONTOITEM { get; set; }
        public Nullable<decimal> ACRESCIMOITEM { get; set; }
        public Nullable<decimal> VALORTOTALLIQUIDO { get; set; }
        public string SITUACAOTRIBUTARIA { get; set; }
        public Nullable<decimal> ALIQUOTA { get; set; }
        public string INDICADORCANCELAMENTO { get; set; }
        public Nullable<int> DECIMAISQTDE { get; set; }
        public Nullable<int> DECIMAISVALORUNITARIO { get; set; }
        public Nullable<int> CODITEMORCAMENTO { get; set; }
        public Nullable<int> CODITEMPEDIDOVENDA { get; set; }
        public Nullable<int> CODITEMCONDICIONAL { get; set; }
        public Nullable<int> CODITEMOS { get; set; }
        public string MD5ITEMDAV { get; set; }
    }
}
