//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDOCDESCARREGAMENTOMDFE
    {
        public int CONTROLE { get; set; }
        public string CHAVECTE { get; set; }
        public string CHAVENFE { get; set; }
        public string CODBARRAS { get; set; }
        public Nullable<int> CODMDFE { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public Nullable<int> CODDESCARREGAMENTO { get; set; }
    }
}
