//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMITENTE
    {
        public TEMITENTE()
        {
            this.TCLIENTE = new HashSet<TCLIENTE>();
            this.TESTOQUE = new HashSet<TESTOQUE>();
            this.TFORNECEDOR = new HashSet<TFORNECEDOR>();
        }
    
        public int CONTROLE { get; set; }
        public string NOMEFANTASIA { get; set; }
        public string RAZAOSOCIAL { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string BAIRRO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string OBS { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string ATIVIDADE { get; set; }
        public string CNAE { get; set; }
        public string CRT { get; set; }
        public Nullable<System.DateTime> DATAFUNDACAOEMPRESA { get; set; }
        public byte[] LOGOTIPO { get; set; }
        public string PAIS { get; set; }
        public string NUMERO { get; set; }
        public Nullable<decimal> PERCICMS { get; set; }
        public Nullable<int> CODICMS { get; set; }
        public string CODCIDADEIBGE { get; set; }
        public Nullable<System.DateTime> DATAMOVIMENTO { get; set; }
        public Nullable<System.TimeSpan> HORAPRIMEIRODOCUMENTOECF { get; set; }
        public string SUFRAMA { get; set; }
        public string SERIEECF { get; set; }
        public string MARCAECF { get; set; }
        public string MODELOECF { get; set; }
        public string TIPOECF { get; set; }
        public string MD5 { get; set; }
        public string VERIFICADORFB { get; set; }
        public Nullable<System.DateTime> DATAHORAVERIFICACAORFB { get; set; }
        public string CAPTCHARFB { get; set; }
        public string RETORNORFB { get; set; }
        public string AUTORIZADOUSO { get; set; }
        public string MD5CNPJRAZAOUFRFB { get; set; }
        public string SERIALINSTALADO { get; set; }
        public Nullable<decimal> ALIQUOTAISSQN { get; set; }
        public Nullable<int> CODIMPOSTOISS { get; set; }
        public string NOTALEGALDF { get; set; }
        public string E3SERIEECF { get; set; }
        public string E3TIPOECF { get; set; }
        public string E3MARCAECF { get; set; }
        public string E3MODELOECF { get; set; }
        public string ATACADOEVAREJO { get; set; }
        public string MD5BOS { get; set; }
        public string MD5P { get; set; }
        public string MD5L { get; set; }
        public string CPF { get; set; }
        public string MD5V { get; set; }
        public string RNTRC { get; set; }
        public string MD5B { get; set; }
        public string REGIMETRIBUTARIOISSQN { get; set; }
        public string SITE2 { get; set; }
        public string SITE { get; set; }
        public string CNPJCONTADOR { get; set; }
        public Nullable<int> VERSAOSERVIDOR { get; set; }
        public Nullable<int> RELEASESERVIDOR { get; set; }
        public string CHAVEPP { get; set; }
        public string CONTROLESG { get; set; }
        public string MD5PAF { get; set; }
        public string OC { get; set; }
        public Nullable<System.DateTime> DATAIE { get; set; }
    
        public virtual TCIDADE TCIDADE { get; set; }
        public virtual ICollection<TCLIENTE> TCLIENTE { get; set; }
        public virtual TIMPOSTO TIMPOSTO { get; set; }
        public virtual ICollection<TESTOQUE> TESTOQUE { get; set; }
        public virtual ICollection<TFORNECEDOR> TFORNECEDOR { get; set; }
    }
}
