//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTADOSICMSSUBS
    {
        public int CONTROLE { get; set; }
        public string UF { get; set; }
        public decimal MVAAJUSTADO { get; set; }
        public decimal PERCICMSPROPRIO { get; set; }
        public decimal PERCICMSST { get; set; }
        public int CODPRODUTO { get; set; }
        public string CSOSN { get; set; }
        public Nullable<decimal> ALIQUOTAINTERESTADUAL { get; set; }
        public Nullable<decimal> ALIQUOTAINTERNADESTINO { get; set; }
        public Nullable<decimal> ALIQUOTAAPROVEITAMENTO { get; set; }
        public Nullable<decimal> PERCREDUCAOBC { get; set; }
    }
}
