//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TETIQUETA
    {
        public int CONTROLE { get; set; }
        public string NOME { get; set; }
        public string MODELO { get; set; }
        public string TAMALTURA { get; set; }
        public string TAMLARGURA { get; set; }
        public string ALTURAETIQUETA { get; set; }
        public string QTDECOLUNAS { get; set; }
        public string ESPACOETIQUETA { get; set; }
        public string MARGEMCIMA { get; set; }
        public string MARGEMBAIXO { get; set; }
        public string MARGEMDIREITA { get; set; }
        public string MARGEMESQUERDA { get; set; }
        public Nullable<int> TOPCODBARRAS { get; set; }
        public Nullable<int> LEFTCODBARRAS { get; set; }
        public Nullable<int> TOPCODBARRAS2 { get; set; }
        public Nullable<int> LEFTCODBARRAS2 { get; set; }
        public string PALAVRA { get; set; }
        public Nullable<int> TOPPALAVRA { get; set; }
        public Nullable<int> LEFTPALAVRA { get; set; }
        public Nullable<int> TOPPRECOVENDA { get; set; }
        public Nullable<int> LEFTPRECOVENDA { get; set; }
        public Nullable<int> TOPPRECOCUSTO { get; set; }
        public Nullable<int> LEFTPRECOCUSTO { get; set; }
        public Nullable<int> TOPDESCRICAO { get; set; }
        public Nullable<int> LEFTDESCRICAO { get; set; }
        public Nullable<int> TOPREFERENCIA { get; set; }
        public Nullable<int> LEFTREFERENCIA { get; set; }
        public Nullable<int> TOPQTDE { get; set; }
        public Nullable<int> LEFTQTDE { get; set; }
        public Nullable<int> TOPLOGO { get; set; }
        public Nullable<int> LEFTLOGO { get; set; }
        public string ALTURALOGO { get; set; }
        public string LARGURALOGO { get; set; }
        public Nullable<int> ALTURACODBARRAS { get; set; }
        public Nullable<int> ALTURACODBARRAS2 { get; set; }
        public Nullable<int> TOPEMITENTE { get; set; }
        public Nullable<int> LEFTEMITENTE { get; set; }
        public Nullable<int> TOPCODIGO { get; set; }
        public Nullable<int> LEFTCODIGO { get; set; }
        public Nullable<int> TOPPALAVRA2 { get; set; }
        public Nullable<int> LEFTPALAVRA2 { get; set; }
        public Nullable<int> TOPDESCRICAO2 { get; set; }
        public Nullable<int> LEFTDESCRICAO2 { get; set; }
        public Nullable<int> TOPPRECOVENDA2 { get; set; }
        public Nullable<int> LEFTPRECOVENDA2 { get; set; }
        public string PALAVRA2 { get; set; }
        public Nullable<int> TOPCODIGO2 { get; set; }
        public Nullable<int> LEFTCODIGO2 { get; set; }
        public string FONTECODIGO { get; set; }
        public string ESTILOCODIGO { get; set; }
        public Nullable<int> TAMANHOCODIGO { get; set; }
        public string FONTECODIGO2 { get; set; }
        public string ESTILOCODIGO2 { get; set; }
        public Nullable<int> TAMANHOCODIGO2 { get; set; }
        public string FONTECODBARRAS { get; set; }
        public Nullable<int> TAMANHOCODBARRAS { get; set; }
        public string FONTECODBARRAS2 { get; set; }
        public string ESTILOCODBARRAS2 { get; set; }
        public Nullable<int> TAMANHOCODBARRAS2 { get; set; }
        public string FONTEPALAVRA { get; set; }
        public string ESTILOPALAVRA { get; set; }
        public Nullable<int> TAMANHOPALAVRA { get; set; }
        public string FONTEPALAVRA2 { get; set; }
        public string ESTILOPALAVRA2 { get; set; }
        public Nullable<int> TAMANHOPALAVRA2 { get; set; }
        public string FONTEDESCRICAO { get; set; }
        public string ESTILODESCRICAO { get; set; }
        public Nullable<int> TAMANHODESCRICAO { get; set; }
        public string FONTEDESCRICAO2 { get; set; }
        public string ESTILODESCRICAO2 { get; set; }
        public Nullable<int> TAMANHODESCRICAO2 { get; set; }
        public string FONTEREFERENCIA { get; set; }
        public string ESTILOREFERENCIA { get; set; }
        public Nullable<int> TAMANHOREFERENCIA { get; set; }
        public string FONTEQTDE { get; set; }
        public string ESTILOQTDE { get; set; }
        public Nullable<int> TAMANHOQTDE { get; set; }
        public string FONTEPRECOVENDA { get; set; }
        public string ESTILOPRECOVENDA { get; set; }
        public Nullable<int> TAMANHOPRECOVENDA { get; set; }
        public string FONTEPRECOVENDA2 { get; set; }
        public string ESTILOPRECOVENDA2 { get; set; }
        public Nullable<int> TAMANHOPRECOVENDA2 { get; set; }
        public string FONTEPRECOCUSTO { get; set; }
        public string ESTILOPRECOCUSTO { get; set; }
        public Nullable<int> TAMANHOPRECOCUSTO { get; set; }
        public string FONTEEMITENTE { get; set; }
        public string ESTILOEMITENTE { get; set; }
        public Nullable<int> TAMANHOEMITENTE { get; set; }
        public string MODOIMPRESSAO { get; set; }
        public string ESTILOCODBARRAS { get; set; }
        public Nullable<int> ALTURADESCRICAO { get; set; }
        public Nullable<int> LARGURADESCRICAO { get; set; }
        public Nullable<int> ALTURADESCRICAO2 { get; set; }
        public Nullable<int> LARGURADESCRICAO2 { get; set; }
        public Nullable<int> TOPUN { get; set; }
        public Nullable<int> LEFTUN { get; set; }
        public string FONTEUN { get; set; }
        public Nullable<int> TAMANHOUN { get; set; }
        public string ESTILOUN { get; set; }
    }
}
