//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFORMAPAGAMENTOOS
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public Nullable<int> CODPLANOCONTA { get; set; }
        public string PLANOCONTA { get; set; }
        public Nullable<int> CODOS { get; set; }
        public string TIPOLANCAMENTOFINANCEIRO { get; set; }
        public string TIPOCARTAO { get; set; }
        public string TIPOASSOCIACAO { get; set; }
        public Nullable<decimal> VALORTROCO { get; set; }
        public Nullable<System.DateTime> DATALANCAMENTO { get; set; }
        public string VALORPAGOVARCHAR { get; set; }
        public Nullable<decimal> VALORPAGO { get; set; }
    }
}
