//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFORMAPAGAMENTOALUGUEL
    {
        public TFORMAPAGAMENTOALUGUEL()
        {
            this.TALUGUEL = new HashSet<TALUGUEL>();
        }
    
        public int CONTROLE { get; set; }
        public int CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public int CODPLANOCONTA { get; set; }
        public string PLANOCONTA { get; set; }
        public int CODALUGUEL { get; set; }
        public string TIPOLANCAMENTOFINANCEIRO { get; set; }
        public string TIPOCARTAO { get; set; }
        public string TIPOASSOCIACAO { get; set; }
        public decimal VALORTROCO { get; set; }
        public System.DateTime DATALANCAMENTO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string VALORPAGOVARCHAR { get; set; }
        public decimal VALORPAGO { get; set; }
        public Nullable<int> CODCAIXA { get; set; }
        public Nullable<int> CODRECEBER { get; set; }
    
        public virtual ICollection<TALUGUEL> TALUGUEL { get; set; }
        public virtual TALUGUEL TALUGUEL1 { get; set; }
        public virtual TCAIXA TCAIXA { get; set; }
        public virtual TESPECIE TESPECIE { get; set; }
        public virtual TPLANOCONTA TPLANOCONTA { get; set; }
        public virtual TRECEBER TRECEBER { get; set; }
    }
}
