//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFUNCIONARIO
    {
        public TFUNCIONARIO()
        {
            this.TAJUSTEESTOQUE = new HashSet<TAJUSTEESTOQUE>();
            this.TALUGUEL = new HashSet<TALUGUEL>();
            this.TALUGUEL1 = new HashSet<TALUGUEL>();
            this.TCLIENTE = new HashSet<TCLIENTE>();
            this.TCOMANDA = new HashSet<TCOMANDA>();
            this.TCONDICIONAL = new HashSet<TCONDICIONAL>();
            this.TCONDICIONAL1 = new HashSet<TCONDICIONAL>();
            this.TITEMCOMANDA = new HashSet<TITEMCOMANDA>();
            this.TITEMOPCOMPOSICAO = new HashSet<TITEMOPCOMPOSICAO>();
            this.TITEMORDEMPRODUCAO = new HashSet<TITEMORDEMPRODUCAO>();
            this.TITEMOS = new HashSet<TITEMOS>();
            this.TNOTACONSUMIDOR = new HashSet<TNOTACONSUMIDOR>();
            this.TORCAMENTO = new HashSet<TORCAMENTO>();
            this.TORCAMENTO1 = new HashSet<TORCAMENTO>();
            this.TOS = new HashSet<TOS>();
            this.TOS1 = new HashSet<TOS>();
            this.TPAGAR = new HashSet<TPAGAR>();
            this.TPEDIDOVENDA = new HashSet<TPEDIDOVENDA>();
            this.TPEDIDOVENDA1 = new HashSet<TPEDIDOVENDA>();
            this.TPREVENDA = new HashSet<TPREVENDA>();
            this.TRECEBER = new HashSet<TRECEBER>();
            this.TUSUARIO = new HashSet<TUSUARIO>();
            this.TVENDAECF = new HashSet<TVENDAECF>();
            this.TVENDANFCE = new HashSet<TVENDANFCE>();
            this.TVENDANFE = new HashSet<TVENDANFE>();
        }
    
        public int CONTROLE { get; set; }
        public string FUNCIONARIO { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string EMAIL { get; set; }
        public string PAI { get; set; }
        public string MAE { get; set; }
        public System.DateTime DATANASCIMENTO { get; set; }
        public Nullable<int> CODFUNCAO { get; set; }
        public string FUNCAO { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> PERCCOMISSAO { get; set; }
        public Nullable<decimal> VALORCOMISSAO { get; set; }
        public Nullable<decimal> SALARIOFIXO { get; set; }
        public Nullable<decimal> SALARIOBASE { get; set; }
        public Nullable<decimal> SALARIOAPROXIMADO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string NATURALIDADE { get; set; }
        public string NACIONALIDADE { get; set; }
        public string ATIVO { get; set; }
        public Nullable<System.DateTime> DATAADMISSAO { get; set; }
        public Nullable<System.DateTime> DATADEMISSAO { get; set; }
        public string TECNICO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string NUMERO { get; set; }
        public string CTPS { get; set; }
        public string FOTOASSINATURA { get; set; }
    
        public virtual ICollection<TAJUSTEESTOQUE> TAJUSTEESTOQUE { get; set; }
        public virtual ICollection<TALUGUEL> TALUGUEL { get; set; }
        public virtual ICollection<TALUGUEL> TALUGUEL1 { get; set; }
        public virtual ICollection<TCLIENTE> TCLIENTE { get; set; }
        public virtual ICollection<TCOMANDA> TCOMANDA { get; set; }
        public virtual ICollection<TCONDICIONAL> TCONDICIONAL { get; set; }
        public virtual ICollection<TCONDICIONAL> TCONDICIONAL1 { get; set; }
        public virtual TFUNCAO TFUNCAO { get; set; }
        public virtual ICollection<TITEMCOMANDA> TITEMCOMANDA { get; set; }
        public virtual ICollection<TITEMOPCOMPOSICAO> TITEMOPCOMPOSICAO { get; set; }
        public virtual ICollection<TITEMORDEMPRODUCAO> TITEMORDEMPRODUCAO { get; set; }
        public virtual ICollection<TITEMOS> TITEMOS { get; set; }
        public virtual ICollection<TNOTACONSUMIDOR> TNOTACONSUMIDOR { get; set; }
        public virtual ICollection<TORCAMENTO> TORCAMENTO { get; set; }
        public virtual ICollection<TORCAMENTO> TORCAMENTO1 { get; set; }
        public virtual ICollection<TOS> TOS { get; set; }
        public virtual ICollection<TOS> TOS1 { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
        public virtual ICollection<TPEDIDOVENDA> TPEDIDOVENDA { get; set; }
        public virtual ICollection<TPEDIDOVENDA> TPEDIDOVENDA1 { get; set; }
        public virtual ICollection<TPREVENDA> TPREVENDA { get; set; }
        public virtual ICollection<TRECEBER> TRECEBER { get; set; }
        public virtual ICollection<TUSUARIO> TUSUARIO { get; set; }
        public virtual ICollection<TVENDAECF> TVENDAECF { get; set; }
        public virtual ICollection<TVENDANFCE> TVENDANFCE { get; set; }
        public virtual ICollection<TVENDANFE> TVENDANFE { get; set; }
    }
}
