//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGRADE
    {
        public TGRADE()
        {
            this.TITEMCOMPRAGRADE = new HashSet<TITEMCOMPRAGRADE>();
            this.TITEMCONDICIONALGRADE = new HashSet<TITEMCONDICIONALGRADE>();
            this.TITEMECFGRADE = new HashSet<TITEMECFGRADE>();
            this.TITEMNFCEGRADE = new HashSet<TITEMNFCEGRADE>();
            this.TITEMORCAMENTOGRADE = new HashSet<TITEMORCAMENTOGRADE>();
            this.TITEMPEDIDOVENDAGRADE = new HashSet<TITEMPEDIDOVENDAGRADE>();
            this.TITEMPREVENDAGRADE = new HashSet<TITEMPREVENDAGRADE>();
            this.TITENNFEGRADE = new HashSet<TITENNFEGRADE>();
        }
    
        public int CONTROLE { get; set; }
        public string COR { get; set; }
        public string TAMANHO { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public decimal QUANTIDADE { get; set; }
    
        public virtual ICollection<TITEMCOMPRAGRADE> TITEMCOMPRAGRADE { get; set; }
        public virtual ICollection<TITEMCONDICIONALGRADE> TITEMCONDICIONALGRADE { get; set; }
        public virtual ICollection<TITEMECFGRADE> TITEMECFGRADE { get; set; }
        public virtual ICollection<TITEMNFCEGRADE> TITEMNFCEGRADE { get; set; }
        public virtual ICollection<TITEMORCAMENTOGRADE> TITEMORCAMENTOGRADE { get; set; }
        public virtual ICollection<TITEMPEDIDOVENDAGRADE> TITEMPEDIDOVENDAGRADE { get; set; }
        public virtual ICollection<TITEMPREVENDAGRADE> TITEMPREVENDAGRADE { get; set; }
        public virtual ICollection<TITENNFEGRADE> TITENNFEGRADE { get; set; }
    }
}
