//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGRADEITEMPEDIDOCOMPRA
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODITEMPEDIDOCOMPRA { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public Nullable<int> CODIGOGRADE { get; set; }
        public string PRODUTO { get; set; }
        public string COR { get; set; }
        public string TAMANHO { get; set; }
        public Nullable<decimal> QUANTIDADE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<int> CODPEDIDOCOMPRA { get; set; }
    }
}
