//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGRUPOESTOQUE
    {
        public TGRUPOESTOQUE()
        {
            this.TESTOQUE = new HashSet<TESTOQUE>();
            this.TITEMTABELAPRECO = new HashSet<TITEMTABELAPRECO>();
            this.TSUBGRUPOESTOQUE = new HashSet<TSUBGRUPOESTOQUE>();
        }
    
        public int CONTROLE { get; set; }
        public string GRUPO { get; set; }
        public string IMPRESSORACOMANDA { get; set; }
    
        public virtual ICollection<TESTOQUE> TESTOQUE { get; set; }
        public virtual ICollection<TITEMTABELAPRECO> TITEMTABELAPRECO { get; set; }
        public virtual ICollection<TSUBGRUPOESTOQUE> TSUBGRUPOESTOQUE { get; set; }
    }
}
