//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGRUPOCLIENTE
    {
        public TGRUPOCLIENTE()
        {
            this.TCLIENTE = new HashSet<TCLIENTE>();
        }
    
        public int CONTROLE { get; set; }
        public string GRUPO { get; set; }
    
        public virtual ICollection<TCLIENTE> TCLIENTE { get; set; }
    }
}
