//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THISTORICOSERIAL
    {
        public int CONTROLE { get; set; }
        public string SERIAL { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public string FORNECEDOR { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public Nullable<System.DateTime> DATACOMPRA { get; set; }
        public Nullable<System.DateTime> DATAVENDA { get; set; }
        public Nullable<int> CODSERIAL { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string FINALIZADO { get; set; }
        public string FINALIZADOCOMPRA { get; set; }
    }
}
