//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMPOSTOMEDIO
    {
        public TIMPOSTOMEDIO()
        {
            this.TESTOQUE = new HashSet<TESTOQUE>();
            this.TOS = new HashSet<TOS>();
        }
    
        public int CONTROLE { get; set; }
        public string NCMNBS { get; set; }
        public Nullable<int> EXCECAOFISCAL { get; set; }
        public string DESCRICAO { get; set; }
        public string EPRODUTO { get; set; }
        public string ESERVICO { get; set; }
        public Nullable<decimal> ALIQUOTANACIONAL { get; set; }
        public Nullable<decimal> ALIQUOTAIMPORTADA { get; set; }
        public string VERSAOTABELA { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAHORAALTERACAO { get; set; }
        public Nullable<decimal> ALIQUOTAESTADUAL { get; set; }
        public Nullable<decimal> ALIQUOTAMUNICIPAL { get; set; }
        public string CEST { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<TESTOQUE> TESTOQUE { get; set; }
        public virtual ICollection<TOS> TOS { get; set; }
    }
}
