//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMPOSTOISS
    {
        public int CONTROLE { get; set; }
        public string DESCRICAORECEITA { get; set; }
        public Nullable<decimal> ALIQUOTA { get; set; }
        public Nullable<decimal> IRPJ { get; set; }
        public Nullable<decimal> CSLL { get; set; }
        public Nullable<decimal> COFINS { get; set; }
        public Nullable<decimal> CPP { get; set; }
        public decimal ALIQUOTAISS { get; set; }
        public Nullable<decimal> PISPASEP { get; set; }
    }
}
