//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMCOMANDA
    {
        public TITEMCOMANDA()
        {
            this.TITEMCOMANDAADICIONAL = new HashSet<TITEMCOMANDAADICIONAL>();
        }
    
        public int CONTROLE { get; set; }
        public int CODCOMANDA { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string CODIGOBARRA { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
        public string CANCELADO { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public string TRASFERIDO { get; set; }
        public Nullable<int> MESAORIGEM { get; set; }
        public Nullable<int> MESADESTINO { get; set; }
        public Nullable<System.DateTime> DATALANCAMENTO { get; set; }
        public Nullable<System.TimeSpan> HORALANCAMENTO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public string UN { get; set; }
        public string CHECADO { get; set; }
        public string DESCRICAOTRANSFERENCIA { get; set; }
        public string STATUS { get; set; }
        public string ADICIONAIS { get; set; }
        public string CONFIRMADO { get; set; }
        public string IMPRESSO { get; set; }
        public Nullable<decimal> VALORADICIONAL { get; set; }
        public string OBSITEM { get; set; }
        public string IMPRESSORA { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public string NOMEPC { get; set; }
        public Nullable<System.DateTime> DATAEHORACANCELAMENTO { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string MD5 { get; set; }
        public Nullable<int> CONTROLEBASEMOBILE { get; set; }
        public string IMEIMOBILE { get; set; }
        public string CANCELAMENTOIMPRESSO { get; set; }
    
        public virtual TCOMANDA TCOMANDA { get; set; }
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual ICollection<TITEMCOMANDAADICIONAL> TITEMCOMANDAADICIONAL { get; set; }
    }
}
