//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMALUGUEL
    {
        public int CONTROLE { get; set; }
        public int CODALUGUEL { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public string STATUS { get; set; }
        public string REFERENCIA { get; set; }
        public string CANCELADO { get; set; }
        public Nullable<decimal> ALIQUOTA { get; set; }
        public string SITUACAOTRIBUTARIA { get; set; }
        public Nullable<int> DECIMAISQTDE { get; set; }
        public Nullable<int> DECIMAISVALORUNITARIO { get; set; }
        public string ALUGADO { get; set; }
        public string JAALUGADO { get; set; }
        public Nullable<System.DateTime> DATAINICIAL { get; set; }
        public Nullable<System.DateTime> DATAPREVISAOENTREGA { get; set; }
        public Nullable<System.DateTime> DATAPREVISAODEVOLUCAO { get; set; }
        public Nullable<System.DateTime> DATADEVOLUCAO { get; set; }
    
        public virtual TALUGUEL TALUGUEL { get; set; }
        public virtual TESTOQUE TESTOQUE { get; set; }
    }
}
