//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMCONDICIONAL
    {
        public TITEMCONDICIONAL()
        {
            this.TITEMCONDICIONALGRADE = new HashSet<TITEMCONDICIONALGRADE>();
            this.TITEMCONDICIONALSERIAL = new HashSet<TITEMCONDICIONALSERIAL>();
        }
    
        public int CONTROLE { get; set; }
        public int CODCONDICIONAL { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public decimal VALORUNITARIO { get; set; }
        public decimal VALORTOTAL { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string DEVOLVIDO { get; set; }
        public string UN { get; set; }
        public string SITUACAOTRIBUTARIA { get; set; }
        public decimal ALIQUOTA { get; set; }
        public string CANCELADO { get; set; }
        public int DECIMAISQTDE { get; set; }
        public int DECIMAISVALORUNITARIO { get; set; }
        public Nullable<int> CODITEM { get; set; }
        public string NUMERODAV { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public string MD5ITEMDAV { get; set; }
        public string MESCLAR { get; set; }
        public string STATUS { get; set; }
        public string CFOP { get; set; }
        public string CODBARRAS { get; set; }
        public Nullable<decimal> QTDE { get; set; }
    
        public virtual TCONDICIONAL TCONDICIONAL { get; set; }
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual ICollection<TITEMCONDICIONALGRADE> TITEMCONDICIONALGRADE { get; set; }
        public virtual ICollection<TITEMCONDICIONALSERIAL> TITEMCONDICIONALSERIAL { get; set; }
    }
}
