//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMNOTACONSUMIDORSERIAL
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string SERIAL { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<int> CODNOTACONSUMIDOR { get; set; }
        public Nullable<int> CODITEMNOTACONSUMIDOR { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
    }
}
