//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMNFEVEICULO
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODITEMVENDANFE { get; set; }
        public Nullable<int> CODVENDANFE { get; set; }
        public string TIPOOPERACAO { get; set; }
        public string CHASSI { get; set; }
        public string CODIGOCOR { get; set; }
        public string POTENCIAMOTOR { get; set; }
        public string CILINDRADAS { get; set; }
        public Nullable<decimal> PESOLIQUIDO { get; set; }
        public Nullable<decimal> PESOBRUTO { get; set; }
        public string NUMEROSERIE { get; set; }
        public string TIPOCOMBUSTIVEL { get; set; }
        public string NUMEROMOTOR { get; set; }
        public Nullable<decimal> CAPACIDADEMAXIMATRACAO { get; set; }
        public string DISTANCIAEIXOS { get; set; }
        public string ANOMODELOFABRICACAO { get; set; }
        public string TIPOPINTURA { get; set; }
        public string TIPOVEICULO { get; set; }
        public string ESPECIEVEICULO { get; set; }
        public string CONDICAOVIN { get; set; }
        public string CONDICAOVEICULO { get; set; }
        public string CODIGOMARCARENAVAN { get; set; }
        public string CAPACIDADEMAXIMA { get; set; }
        public string RESTRICAO { get; set; }
        public Nullable<int> ANOFABRICACAO { get; set; }
    
        public virtual TITENSVENDANFE TITENSVENDANFE { get; set; }
        public virtual TVENDANFE TVENDANFE { get; set; }
    }
}
