//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITENNOTACONSUMIDOR
    {
        public TITENNOTACONSUMIDOR()
        {
            this.TITEMNOTACONSUMIDORGRADE = new HashSet<TITEMNOTACONSUMIDORGRADE>();
        }
    
        public int CONTROLE { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public Nullable<decimal> TOTALITENS { get; set; }
        public Nullable<int> CODNOTACONSUMIDOR { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string NUMERONOTA { get; set; }
        public Nullable<int> NUMEROITENS { get; set; }
        public Nullable<int> CODUNIDADEMEDIDA { get; set; }
        public string UNIDADE { get; set; }
        public string CODAPLICACAOPRODUTO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORBASECALCULO { get; set; }
        public Nullable<decimal> VALORICMS { get; set; }
        public Nullable<decimal> VALORPIS { get; set; }
        public Nullable<decimal> VALORCOFINS { get; set; }
        public string CANCELADO { get; set; }
        public string USAGRADE { get; set; }
        public string CONFIRMADO { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public Nullable<decimal> PRECOCUSTOITEM { get; set; }
        public Nullable<decimal> PERCICMS { get; set; }
        public Nullable<decimal> PERCCOMISSAO { get; set; }
        public string CSOSN { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> VALORIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> TOTALCOMISSAO { get; set; }
        public Nullable<decimal> QTDE2 { get; set; }
        public Nullable<decimal> PRECOUNITARIO2 { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<decimal> PRECOUNITARIO { get; set; }
    
        public virtual ICollection<TITEMNOTACONSUMIDORGRADE> TITEMNOTACONSUMIDORGRADE { get; set; }
        public virtual TNOTACONSUMIDOR TNOTACONSUMIDOR { get; set; }
    }
}
