//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMCOMPRAGRADE
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string COR { get; set; }
        public string TAMANHO { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<int> CODITEMCOMPRA { get; set; }
        public Nullable<int> NOTACOMPRA { get; set; }
        public Nullable<int> CODGRADE { get; set; }
        public Nullable<int> CODCOMPRA { get; set; }
    
        public virtual TCOMPRA TCOMPRA { get; set; }
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TGRADE TGRADE { get; set; }
        public virtual TITEMCOMPRA TITEMCOMPRA { get; set; }
    }
}
