//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMPEDIDOCOMPRA
    {
        public int CONTROLE { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<decimal> PRECOCUSTO { get; set; }
        public Nullable<decimal> VALORTOTAL { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public Nullable<int> CODPEDIDOCOMPRA { get; set; }
        public Nullable<int> CODGRADE { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> QUANTIDADE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string USAGRADE { get; set; }
        public string UN { get; set; }
        public string REFERENCIA { get; set; }
        public string ESTOQUE { get; set; }
        public string SITUACAOPEDIDO { get; set; }
    
        public virtual TPEDIDOCOMPRA TPEDIDOCOMPRA { get; set; }
    }
}
