//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITENSORCAMENTO
    {
        public TITENSORCAMENTO()
        {
            this.TITEMORCAMENTOGRADE = new HashSet<TITEMORCAMENTOGRADE>();
            this.TITEMORCAMENTOSERIAL = new HashSet<TITEMORCAMENTOSERIAL>();
        }
    
        public int CONTROLE { get; set; }
        public int CODORCAMENTO { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<int> CODITEM { get; set; }
        public string UN { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<decimal> VALORDESCONTOUNITARIO { get; set; }
        public Nullable<decimal> PERCDESCONTOUNITARIO { get; set; }
        public Nullable<decimal> VALORACRESCIMOUNITARIO { get; set; }
        public Nullable<decimal> PERCACRESCIMOUNITARIO { get; set; }
        public string INDICADORCANCELAMENTO { get; set; }
        public Nullable<int> DECIMAISQTDE { get; set; }
        public Nullable<int> DECIMAISVALORUNITARIO { get; set; }
        public string SITUACAOTRIBUTARIA { get; set; }
        public Nullable<decimal> ALIQUOTA { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
        public Nullable<decimal> TOTALLIQUIDO { get; set; }
        public Nullable<decimal> TOTALDESCONTO { get; set; }
        public Nullable<int> CONTROLEORIGEMMESCLAGEM { get; set; }
        public string NUMERODAV { get; set; }
        public string MD5DAV { get; set; }
        public string MESCLAR { get; set; }
        public string STATUS { get; set; }
        public string CFOP { get; set; }
        public Nullable<decimal> TOTALACRESCIMO { get; set; }
        public string REFERENCIA { get; set; }
        public string DESCRICAOCOMPLEMENTAR { get; set; }
        public Nullable<decimal> QTDECONVERTIDA { get; set; }
        public string UNCONVERTIDA { get; set; }
        public Nullable<int> CODAPLICACAOPRODUTO { get; set; }
    
        public virtual ICollection<TITEMORCAMENTOGRADE> TITEMORCAMENTOGRADE { get; set; }
        public virtual ICollection<TITEMORCAMENTOSERIAL> TITEMORCAMENTOSERIAL { get; set; }
        public virtual TORCAMENTO TORCAMENTO { get; set; }
    }
}
