//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMCONTAGEMESTOQUE
    {
        public int CONTROLE { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string CODBARRAS { get; set; }
        public decimal QTDEATUAL { get; set; }
        public decimal QTDECONTADA { get; set; }
        public decimal QTDEAJUSTAR { get; set; }
        public decimal PRECOCUSTO { get; set; }
        public decimal VALORAJUSTADO { get; set; }
        public int CODCONTAGEMESTOQUE { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
    
        public virtual TCONTAGEMESTOQUE TCONTAGEMESTOQUE { get; set; }
    }
}
