//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMTABELAPRECO
    {
        public int CONTROLE { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public int CODTABELAPRECO { get; set; }
        public Nullable<int> CODGRUPOESTOQUE { get; set; }
        public string GRUPOESTOQUE { get; set; }
        public decimal PRECOVENDA { get; set; }
        public decimal PRECOVENDATABELADO { get; set; }
    
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TGRUPOESTOQUE TGRUPOESTOQUE { get; set; }
        public virtual TTABELAPRECO TTABELAPRECO { get; set; }
    }
}
