//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMORDEMPRODUCAO
    {
        public TITEMORDEMPRODUCAO()
        {
            this.TITEMOPCOMPOSICAO = new HashSet<TITEMOPCOMPOSICAO>();
            this.TITEMOPGRADE = new HashSet<TITEMOPGRADE>();
            this.TPRODUCAOFINALIZADA = new HashSet<TPRODUCAOFINALIZADA>();
        }
    
        public int CONTROLE { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string SITUACAO { get; set; }
        public Nullable<int> CODPRODUCAO { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string UN { get; set; }
        public string FUNCIONARIO { get; set; }
        public string USAGRADE { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<decimal> VALORUNITARIO { get; set; }
    
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual ICollection<TITEMOPCOMPOSICAO> TITEMOPCOMPOSICAO { get; set; }
        public virtual ICollection<TITEMOPGRADE> TITEMOPGRADE { get; set; }
        public virtual TORDEMPRODUCAO TORDEMPRODUCAO { get; set; }
        public virtual ICollection<TPRODUCAOFINALIZADA> TPRODUCAOFINALIZADA { get; set; }
    }
}
