//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMNFEVALIDADEESTOQUE
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODITEMNFE { get; set; }
        public Nullable<int> CODNFE { get; set; }
        public string LOTE { get; set; }
        public Nullable<System.DateTime> DATAVALIDADE { get; set; }
        public Nullable<System.DateTime> DATAFABRICACAO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<int> CODLOTE { get; set; }
        public Nullable<decimal> QTDE { get; set; }
    
        public virtual TVALIDADEESTOQUE TVALIDADEESTOQUE { get; set; }
    }
}
