//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITEMNFCESERIAL
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string SERIAL { get; set; }
        public Nullable<decimal> QTDE { get; set; }
        public Nullable<int> CODITEMVENDANFCE { get; set; }
        public Nullable<int> CODVENDANFCE { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public string CANCELADO { get; set; }
        public Nullable<int> CODSERIAL { get; set; }
    
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TITEMVENDANFCE TITEMVENDANFCE { get; set; }
        public virtual TSERIAL TSERIAL { get; set; }
        public virtual TVENDANFCE TVENDANFCE { get; set; }
    }
}
