//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMEIOPAGAMENTOVENDAECF
    {
        public int CONTROLE { get; set; }
        public System.DateTime DATA { get; set; }
        public System.TimeSpan HORA { get; set; }
        public int CODVENDAECF { get; set; }
        public int CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public int CODESPECIEECF { get; set; }
        public string ESPECIEECF { get; set; }
        public decimal VALORPAGO { get; set; }
        public string TIPODOCUMENTO { get; set; }
        public string TIPOCARTAO { get; set; }
        public int CODNFE { get; set; }
        public string TIPOREGISTRO { get; set; }
        public string CNPJCREDENCIADORA { get; set; }
        public string SERIEECF { get; set; }
        public string MFADICIONAL { get; set; }
        public string TIPOECF { get; set; }
        public string MARCAECF { get; set; }
        public string MODELOECF { get; set; }
        public Nullable<int> COO { get; set; }
        public Nullable<int> CCF { get; set; }
        public Nullable<decimal> VALORTROCO { get; set; }
        public Nullable<System.DateTime> DATADOTROCO { get; set; }
        public string CPF { get; set; }
        public Nullable<int> TITULOCAPITALIZACAO { get; set; }
        public Nullable<int> CODIGOTIPODOCUMENTO { get; set; }
        public string MD5A2 { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
    }
}
