//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMESA
    {
        public int CONTROLE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> NUMEROMESA { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string NOMERESERVA { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public Nullable<System.DateTime> DATAMOVIMENTO { get; set; }
        public string SEMMOVIMENTO { get; set; }
        public string IDENTIFICADOR { get; set; }
    }
}
