//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMOTORISTAMDFE
    {
        public int CONTROLE { get; set; }
        public string NOME { get; set; }
        public string CPF { get; set; }
        public string TIPORODADO { get; set; }
        public string TIPOCARROCERIA { get; set; }
        public Nullable<int> CODMDFE { get; set; }
    }
}
