//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMOTORISTA
    {
        public int CONTROLE { get; set; }
        public string MOTORISTA { get; set; }
        public string CPF { get; set; }
        public Nullable<System.DateTime> DATAEHORACASATRO { get; set; }
    }
}
