//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMOTIVOCANCELAMENTOVENDA
    {
        public TMOTIVOCANCELAMENTOVENDA()
        {
            this.TVENDAECF = new HashSet<TVENDAECF>();
        }
    
        public int CONTROLE { get; set; }
        public string MOTIVO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
    
        public virtual ICollection<TVENDAECF> TVENDAECF { get; set; }
    }
}
