//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMOVBANCO
    {
        public int CONTROLE { get; set; }
        public string DOCUMENTO { get; set; }
        public string HISTORICO { get; set; }
        public decimal VALORENTRADA { get; set; }
        public decimal VALORSAIDA { get; set; }
        public decimal SALDO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string NUMEROCONTA { get; set; }
        public int CODCONTA { get; set; }
        public string BANCO { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> LIMITE { get; set; }
        public string TELEFONE { get; set; }
        public string GERENTEADACONTA { get; set; }
        public Nullable<int> CODRECEBER { get; set; }
        public Nullable<int> CODPAGAR { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public Nullable<int> CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public Nullable<int> CODPLANOCONTA { get; set; }
        public string PLANOCONTA { get; set; }
        public Nullable<System.DateTime> DATARECEBIMENTO { get; set; }
    
        public virtual TCONTABANCARIA TCONTABANCARIA { get; set; }
    }
}
