//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNFCEINUTILIZADA
    {
        public int CONTROLE { get; set; }
        public string MOTIVO { get; set; }
        public string TIPOAMBIENTE { get; set; }
        public Nullable<System.DateTime> DATAEHORARECEBIMENTO { get; set; }
        public string NUMEROINICIAL { get; set; }
        public string NUMEROFINAL { get; set; }
        public string JUSTIFICATIVA { get; set; }
        public string SERIE { get; set; }
        public string ANO { get; set; }
        public string PROTOCOLO { get; set; }
    }
}
