//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNOTACTRC
    {
        public int CONTROLE { get; set; }
        public int CODCTRC { get; set; }
        public string NUMERONF { get; set; }
        public Nullable<System.DateTime> DATAEMISSAONF { get; set; }
        public string CHAVEACESSONF { get; set; }
        public Nullable<decimal> TOTALNF { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
    
        public virtual TCTRC TCTRC { get; set; }
    }
}
