//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOBJETOSOS
    {
        public TOBJETOSOS()
        {
            this.TOS = new HashSet<TOS>();
        }
    
        public int CONTROLE { get; set; }
        public string DESCRICAO { get; set; }
        public string NUMEROCONTRATO { get; set; }
        public Nullable<System.DateTime> DATACONTRATO { get; set; }
        public Nullable<System.DateTime> VALIDADECONTRATO { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public string ATIVO { get; set; }
        public byte[] FOTO { get; set; }
    
        public virtual ICollection<TOS> TOS { get; set; }
    }
}
