//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TORDEMPRODUCAO
    {
        public TORDEMPRODUCAO()
        {
            this.TITEMOPCOMPOSICAO = new HashSet<TITEMOPCOMPOSICAO>();
            this.TITEMOPGRADE = new HashSet<TITEMOPGRADE>();
            this.TITEMORDEMPRODUCAO = new HashSet<TITEMORDEMPRODUCAO>();
            this.TPRODUCAOFINALIZADA = new HashSet<TPRODUCAOFINALIZADA>();
        }
    
        public int CONTROLE { get; set; }
        public System.DateTime DATAEHORACADASTRO { get; set; }
        public string DESCRICAO { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public Nullable<System.DateTime> DATAINICIO { get; set; }
        public Nullable<System.TimeSpan> HORAINICIO { get; set; }
        public Nullable<System.DateTime> DATAFINAL { get; set; }
        public Nullable<System.TimeSpan> HORAFINAL { get; set; }
        public Nullable<decimal> TOTALORDEM { get; set; }
        public Nullable<decimal> TOTALPRODUTOS { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public Nullable<System.DateTime> PREVISAODEENTREGA { get; set; }
        public string LOTE { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> NUMEROPROPRIO { get; set; }
        public string HISTORICOSTATUS { get; set; }
        public Nullable<decimal> QTDEAPRODUZIR { get; set; }
        public Nullable<int> CODFUNCIONARIOCONFERENTE { get; set; }
        public string FUNCIONARIOCONFERENTE { get; set; }
    
        public virtual ICollection<TITEMOPCOMPOSICAO> TITEMOPCOMPOSICAO { get; set; }
        public virtual ICollection<TITEMOPGRADE> TITEMOPGRADE { get; set; }
        public virtual ICollection<TITEMORDEMPRODUCAO> TITEMORDEMPRODUCAO { get; set; }
        public virtual ICollection<TPRODUCAOFINALIZADA> TPRODUCAOFINALIZADA { get; set; }
    }
}
