//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR07
    {
        public int CONTROLE { get; set; }
        public string SERIEECF { get; set; }
        public string MFADICIONAL { get; set; }
        public string MODELOECF { get; set; }
        public int NUMEROUSUARIO { get; set; }
        public int COO { get; set; }
        public int CCF { get; set; }
        public int GNF { get; set; }
        public string MEIOPAGAMENTO { get; set; }
        public decimal VALORPAGO { get; set; }
        public string INDICADORESTORNO { get; set; }
        public decimal VALORESTORNO { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public string DATAEMISSAOS { get; set; }
        public string TIPOCARTAO { get; set; }
        public string MD5R07 { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
