//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR06
    {
        public int CONTROLE { get; set; }
        public string SERIEECF { get; set; }
        public string MFADICIONAL { get; set; }
        public string MODELOECF { get; set; }
        public int NUMEROUSUARIO { get; set; }
        public int COO { get; set; }
        public int GNF { get; set; }
        public int GRG { get; set; }
        public int CDC { get; set; }
        public string DENOMINACAO { get; set; }
        public System.DateTime DATAFINALEMISSAO { get; set; }
        public string DATAFINALEMISSAOS { get; set; }
        public System.TimeSpan HORAFINALEMISSAO { get; set; }
        public string HORAFINALEMISSAOS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string MD5R06 { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
