//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR50
    {
        public int CONTROLE { get; set; }
        public string TIPO { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public string UF { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string NUMERO { get; set; }
        public string CFOP { get; set; }
        public string EMITENTE { get; set; }
        public decimal VALORTOTAL { get; set; }
        public decimal BASECALCULOICMS { get; set; }
        public decimal VALORICMS { get; set; }
        public decimal ISENTAOUNAOTRIBUTADA { get; set; }
        public decimal OUTRAS { get; set; }
        public decimal ALIQUOTA { get; set; }
        public string SITUACAO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
