//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR54
    {
        public int CONTROLE { get; set; }
        public string TIPO { get; set; }
        public string CNPJ { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string NUMERO { get; set; }
        public string CFOP { get; set; }
        public string CST { get; set; }
        public string NUMEROITEM { get; set; }
        public string CODIGOPRODUTO { get; set; }
        public decimal QTDE { get; set; }
        public decimal TOTALBRUTOITEM { get; set; }
        public decimal VALORDESCONTO { get; set; }
        public decimal BASECALCULOICMS { get; set; }
        public decimal BASECALCULOICMSST { get; set; }
        public decimal VALORIPI { get; set; }
        public decimal ALIQUOTAIPI { get; set; }
        public decimal ALIQUOTAICMS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
