//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR61
    {
        public int CONTROLE { get; set; }
        public string TIPO { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string SUBSERIE { get; set; }
        public string NUMEROINICIALDIA { get; set; }
        public string NUMEROFINALDIA { get; set; }
        public decimal VALORTOTAL { get; set; }
        public decimal BASECALCULOICMS { get; set; }
        public decimal VALORICMS { get; set; }
        public decimal VALORISENTO { get; set; }
        public decimal OUTRAS { get; set; }
        public decimal ALIQUOTAICMS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
