//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR60M
    {
        public int CONTROLE { get; set; }
        public string TIPO { get; set; }
        public string SUBTIPO { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public string SERIEECF { get; set; }
        public string NUMEROPDV { get; set; }
        public string MODELODOCUMENTOFISCAL { get; set; }
        public string COOINICIODIA { get; set; }
        public string COOFIMDIA { get; set; }
        public string CRZ { get; set; }
        public string CRO { get; set; }
        public decimal VALORVENDABRUTA { get; set; }
        public decimal VALORTOTALIZADORGERAL { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
