//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAFR60I
    {
        public int CONTROLE { get; set; }
        public string TIPO { get; set; }
        public string SUBTIPO { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public string SERIEECF { get; set; }
        public string MODELODOCUMENTOFISCAL { get; set; }
        public string COO { get; set; }
        public string NUMEROITEM { get; set; }
        public string CODIGOPRODUTO { get; set; }
        public decimal QTDE { get; set; }
        public decimal VALORLIQUIDOPRODUTO { get; set; }
        public decimal BASECALCULOICMS { get; set; }
        public string STOUALIQUOTAICMS { get; set; }
        public decimal VALORICMS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    }
}
