//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAGAMENTOVENDAECF
    {
        public int CONTROLE { get; set; }
        public System.DateTime DATA { get; set; }
        public System.TimeSpan HORA { get; set; }
        public int CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public string CODASSOCIADAECF { get; set; }
        public string ESPECIEECF { get; set; }
        public decimal VALORPAGO { get; set; }
        public decimal VALORCUPOM { get; set; }
        public int COOECF { get; set; }
        public int CCFECF { get; set; }
        public int CODVENDAECF { get; set; }
        public string SERIEECF { get; set; }
        public string TIPOLANCAMENTOFINANCEIRO { get; set; }
        public string TIPOCARTAO { get; set; }
        public string VALORPAGOVARCHAR { get; set; }
    
        public virtual TESPECIE TESPECIE { get; set; }
        public virtual TVENDAECF TVENDAECF { get; set; }
    }
}
