//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAGAR
    {
        public TPAGAR()
        {
            this.TCAIXA = new HashSet<TCAIXA>();
        }
    
        public int CONTROLE { get; set; }
        public string DESCRICAOLANCAMENTO { get; set; }
        public Nullable<int> QTDEPARCELA { get; set; }
        public Nullable<int> NPARCELA { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public string FORNECEDOR { get; set; }
        public Nullable<int> CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAVENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATAPAGAMENTO { get; set; }
        public Nullable<int> DIASATRASO { get; set; }
        public Nullable<int> CODCENTROCUSTO { get; set; }
        public string CENTROCUSTO { get; set; }
        public Nullable<int> CODPLANOCONTA { get; set; }
        public string PLANOCONTA { get; set; }
        public string DOCUMENTO { get; set; }
        public string ORIGEM { get; set; }
        public Nullable<decimal> VALORORIGINAL { get; set; }
        public Nullable<decimal> VALORASERPAGO { get; set; }
        public Nullable<decimal> VALORPAGO { get; set; }
        public Nullable<decimal> PERCDESCONTO { get; set; }
        public Nullable<decimal> PERCACRESCIMO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> PERCMULTA { get; set; }
        public Nullable<decimal> VALORMULTA { get; set; }
        public Nullable<decimal> PERCJUROSAOMES { get; set; }
        public Nullable<decimal> VALORJUROPAGO { get; set; }
        public string CANCELADA { get; set; }
        public string QUITADA { get; set; }
        public Nullable<int> CODPDV { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public byte[] OBS { get; set; }
        public Nullable<decimal> VALORJUROAOMES { get; set; }
        public Nullable<decimal> JUROAODIA { get; set; }
        public Nullable<decimal> VALORJUROAPAGAR { get; set; }
        public string CODBARRA { get; set; }
        public Nullable<int> CODPAGAMENTO { get; set; }
        public Nullable<int> CODPDVPAGAMENTO { get; set; }
        public Nullable<int> CODCOMPRA { get; set; }
        public string REPLICADA { get; set; }
        public Nullable<int> CODCTRC { get; set; }
        public Nullable<int> CODNFE { get; set; }
    
        public virtual ICollection<TCAIXA> TCAIXA { get; set; }
        public virtual TCENTROCUSTO TCENTROCUSTO { get; set; }
        public virtual TCOMPRA TCOMPRA { get; set; }
        public virtual TCTRC TCTRC { get; set; }
        public virtual TESPECIE TESPECIE { get; set; }
        public virtual TFORNECEDOR TFORNECEDOR { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual TPLANOCONTA TPLANOCONTA { get; set; }
        public virtual TVENDANFE TVENDANFE { get; set; }
    }
}
