//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPEDIDOVENDA
    {
        public TPEDIDOVENDA()
        {
            this.TITEMPEDIDOVENDAGRADE = new HashSet<TITEMPEDIDOVENDAGRADE>();
            this.TITEMPEDIDOVENDASERIAL = new HashSet<TITEMPEDIDOVENDASERIAL>();
        }
    
        public int CONTROLE { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string COMPLEMENTO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string CEP { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> QTDEITEM { get; set; }
        public decimal VALORDESCONTO { get; set; }
        public decimal TOTALPRODUTOS { get; set; }
        public decimal TOTALLIQUIDO { get; set; }
        public Nullable<int> COO { get; set; }
        public Nullable<int> CCF { get; set; }
        public string SERIEECF { get; set; }
        public string TIPOECF { get; set; }
        public string MARCAECF { get; set; }
        public string MODELOECF { get; set; }
        public string TITULODAV { get; set; }
        public Nullable<int> COOVINCULADO { get; set; }
        public Nullable<int> NUMEROECF { get; set; }
        public Nullable<int> CODVENDEDOR { get; set; }
        public string VENDEDOR { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public string EMAIL { get; set; }
        public string UF { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string NUMERO { get; set; }
        public string RG { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public string CONTROLEVARCHAR { get; set; }
        public Nullable<int> CODSEQUENCIA { get; set; }
        public string CANCELADO { get; set; }
        public string MESCLAR { get; set; }
        public string MD5DAV { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATAPREVISAOENTREGA { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
    
        public virtual TCIDADE TCIDADE { get; set; }
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO1 { get; set; }
        public virtual ICollection<TITEMPEDIDOVENDAGRADE> TITEMPEDIDOVENDAGRADE { get; set; }
        public virtual ICollection<TITEMPEDIDOVENDASERIAL> TITEMPEDIDOVENDASERIAL { get; set; }
        public virtual TSEQUENCIA TSEQUENCIA { get; set; }
    }
}
