//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPEDIDOCOMPRA
    {
        public TPEDIDOCOMPRA()
        {
            this.TITEMPEDIDOCOMPRA = new HashSet<TITEMPEDIDOCOMPRA>();
        }
    
        public int CONTROLE { get; set; }
        public Nullable<int> CODTRANSPORTADORA { get; set; }
        public int CODFORNECEDOR { get; set; }
        public decimal TOTALPEDIDO { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> PRAZOENTREGA { get; set; }
        public Nullable<System.DateTime> DATAPEDIDO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public string TIPOFRETE { get; set; }
        public string FORMAPEDIDO { get; set; }
        public string SITUACAOPEDIDO { get; set; }
        public Nullable<int> NPARCELAS { get; set; }
        public Nullable<int> INTERVALOPARCELAS { get; set; }
        public Nullable<System.DateTime> INICIODASPARCELAS { get; set; }
        public Nullable<System.DateTime> DATAEHORACADASTRO { get; set; }
        public Nullable<decimal> TOTALRODUTOS { get; set; }
        public string FORMAPAGAMENTO { get; set; }
        public string FORNECEDOR { get; set; }
        public string TRANSPORTADORA { get; set; }
        public Nullable<System.DateTime> PREVISAOENTREGA { get; set; }
        public Nullable<System.DateTime> DATAENTREGA { get; set; }
        public string EMAILFORNECEDOR { get; set; }
        public Nullable<int> CODCOTACAO { get; set; }
    
        public virtual TFORNECEDOR TFORNECEDOR { get; set; }
        public virtual ICollection<TITEMPEDIDOCOMPRA> TITEMPEDIDOCOMPRA { get; set; }
        public virtual TTRANSPORTADORA TTRANSPORTADORA { get; set; }
    }
}
