//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPERFILPAF
    {
        public int CONTROLE { get; set; }
        public string PERFIL { get; set; }
        public int REQUISITO { get; set; }
        public string ITEMREQUISITO { get; set; }
        public string SUBITEMREQUISITO { get; set; }
        public string VERSAOPAF { get; set; }
        public string EXIGENCIA { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string MD5 { get; set; }
    }
}
