//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPERCURSOMDFE
    {
        public int CONTROLE { get; set; }
        public string UF { get; set; }
        public Nullable<System.DateTime> DATAEHORAINICIO { get; set; }
        public Nullable<int> CODMDFE { get; set; }
    
        public virtual TMDFE TMDFE { get; set; }
    }
}
