//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPLANOCONTA
    {
        public TPLANOCONTA()
        {
            this.TCAIXA = new HashSet<TCAIXA>();
            this.TFORMAPAGAMENTOALUGUEL = new HashSet<TFORMAPAGAMENTOALUGUEL>();
            this.TFORMAPAGAMENTOCTE = new HashSet<TFORMAPAGAMENTOCTE>();
            this.TPAGAR = new HashSet<TPAGAR>();
            this.TRECEBER = new HashSet<TRECEBER>();
        }
    
        public int CONTROLE { get; set; }
        public string PLANOCONTA { get; set; }
        public string TIPO { get; set; }
        public string OBS { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
    
        public virtual ICollection<TCAIXA> TCAIXA { get; set; }
        public virtual ICollection<TFORMAPAGAMENTOALUGUEL> TFORMAPAGAMENTOALUGUEL { get; set; }
        public virtual ICollection<TFORMAPAGAMENTOCTE> TFORMAPAGAMENTOCTE { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
        public virtual ICollection<TRECEBER> TRECEBER { get; set; }
    }
}
