//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPRODUCAOFINALIZADA
    {
        public int CONTROLE { get; set; }
        public int CODORDEMPRODUCAO { get; set; }
        public int CODPRODUTOMP { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public int CODITEMPRODUCAO { get; set; }
        public Nullable<decimal> QTDE { get; set; }
    
        public virtual TESTOQUE TESTOQUE { get; set; }
        public virtual TITEMORDEMPRODUCAO TITEMORDEMPRODUCAO { get; set; }
        public virtual TORDEMPRODUCAO TORDEMPRODUCAO { get; set; }
    }
}
