//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREBOQUEMDFE
    {
        public int CONTROLE { get; set; }
        public string CODIGOINTERNO { get; set; }
        public string RENAVAN { get; set; }
        public Nullable<decimal> TARA { get; set; }
        public Nullable<decimal> CAPACIDADEKG { get; set; }
        public Nullable<decimal> CAPACIDADEM3 { get; set; }
        public Nullable<int> CODMDFE { get; set; }
        public string PLACA { get; set; }
    }
}
