//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRECEBER
    {
        public TRECEBER()
        {
            this.TCAIXA = new HashSet<TCAIXA>();
            this.TFORMAPAGAMENTOALUGUEL = new HashSet<TFORMAPAGAMENTOALUGUEL>();
        }
    
        public int CONTROLE { get; set; }
        public string DESCRICAOLANCAMENTO { get; set; }
        public Nullable<int> QTDEPARCELA { get; set; }
        public Nullable<int> NPARCELA { get; set; }
        public int CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public int CODESPECIE { get; set; }
        public string ESPECIE { get; set; }
        public Nullable<System.DateTime> DATAHORACADASTRO { get; set; }
        public Nullable<System.DateTime> DATAVENCIMENTO { get; set; }
        public Nullable<System.DateTime> DATARECEBIMENTO { get; set; }
        public Nullable<int> DIASATRASO { get; set; }
        public int CODCENTROCUSTO { get; set; }
        public string CENTROCUSTO { get; set; }
        public int CODPLANOCONTA { get; set; }
        public string PLANOCONTA { get; set; }
        public string DOCUMENTO { get; set; }
        public string ORIGEM { get; set; }
        public Nullable<decimal> VALORORIGINAL { get; set; }
        public Nullable<decimal> VALORASERPAGO { get; set; }
        public Nullable<decimal> VALORPAGO { get; set; }
        public Nullable<decimal> PERCDESCONTO { get; set; }
        public Nullable<decimal> PERCACRESCIMO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public string REGISTRADOSPC { get; set; }
        public Nullable<decimal> PERCMULTA { get; set; }
        public Nullable<decimal> VALORMULTA { get; set; }
        public Nullable<decimal> PERCJUROSAOMES { get; set; }
        public Nullable<decimal> VALORJUROAOMES { get; set; }
        public Nullable<decimal> VALORJUROPAGO { get; set; }
        public Nullable<decimal> VALORJUROARECEBER { get; set; }
        public string CANCELADA { get; set; }
        public string QUITADA { get; set; }
        public string OBS { get; set; }
        public Nullable<int> CODPDV { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public string CODBARRA { get; set; }
        public Nullable<int> CODPDVRECEBIMENTO { get; set; }
        public Nullable<decimal> VALORVENDA { get; set; }
        public Nullable<decimal> VALORENTRADA { get; set; }
        public string REPLICADA { get; set; }
        public Nullable<int> CODOS { get; set; }
        public Nullable<int> CODNFE { get; set; }
        public string STATUSNFE { get; set; }
        public string MARCADO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> CODNFCE { get; set; }
        public string BOLETOIMPRESSO { get; set; }
        public Nullable<decimal> VALORABATIMENTOBOLETO { get; set; }
        public Nullable<System.DateTime> DATAMORAJUROS { get; set; }
        public Nullable<System.DateTime> DATADESCONTO { get; set; }
        public string NOSSONUMERO { get; set; }
        public string DATAABATIMENTO { get; set; }
        public Nullable<int> CODORIGEMREPLICADA { get; set; }
        public string BOLETOVINCULADO { get; set; }
        public Nullable<int> CODMODULO { get; set; }
        public string VALORANTECIPADO { get; set; }
        public Nullable<int> CODAVALISTA { get; set; }
        public string AVALISTA { get; set; }
        public Nullable<decimal> JUROAODIA { get; set; }
    
        public virtual ICollection<TCAIXA> TCAIXA { get; set; }
        public virtual TCENTROCUSTO TCENTROCUSTO { get; set; }
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual TCLIENTE TCLIENTE1 { get; set; }
        public virtual TESPECIE TESPECIE { get; set; }
        public virtual ICollection<TFORMAPAGAMENTOALUGUEL> TFORMAPAGAMENTOALUGUEL { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual TPLANOCONTA TPLANOCONTA { get; set; }
    }
}
