//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREDUCAOZ
    {
        public TREDUCAOZ()
        {
            this.TDETALHEREDUCAOZ = new HashSet<TDETALHEREDUCAOZ>();
        }
    
        public int CONTROLE { get; set; }
        public string SERIEECF { get; set; }
        public string MODELOECF { get; set; }
        public int NUMEROUSUARIO { get; set; }
        public int CRZ { get; set; }
        public int COO { get; set; }
        public int CRO { get; set; }
        public System.DateTime DATAMOVIMENTO { get; set; }
        public System.TimeSpan HORAEMISSAO { get; set; }
        public System.DateTime DATAEMISSAO { get; set; }
        public decimal VENDABRUTADIARIA { get; set; }
        public string PARAMETROISSQN { get; set; }
        public decimal GRANDETOTAL { get; set; }
        public string MD5R02 { get; set; }
        public string MD5CNPJSERIEECF { get; set; }
        public string TIPOECF { get; set; }
        public string MARCAECF { get; set; }
        public string VERSAOSB { get; set; }
        public Nullable<System.DateTime> DATAINSTALACAOSB { get; set; }
        public Nullable<System.TimeSpan> HORAINSTALACAOSB { get; set; }
        public string CNPJEMITENTE { get; set; }
        public string IEEMITENTE { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
    
        public virtual ICollection<TDETALHEREDUCAOZ> TDETALHEREDUCAOZ { get; set; }
    }
}
