//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEQUENCIANFE
    {
        public int NUMERNOTA { get; set; }
        public Nullable<int> NUMERONOTAHOMOLOGACAO { get; set; }
        public Nullable<int> NUMERONFCEHOMOLOGACAO { get; set; }
        public Nullable<int> NUMERONFCE { get; set; }
        public Nullable<int> NUMEROCTEHOMOLOGACAO { get; set; }
        public Nullable<int> NUMEROCTE { get; set; }
        public Nullable<int> NUMEROSAT { get; set; }
        public Nullable<int> NUMEROMDFE { get; set; }
        public Nullable<int> NUMEROMDFEHOMOLOGACAO { get; set; }
    }
}
