//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSEQUENCIA
    {
        public TSEQUENCIA()
        {
            this.TCONDICIONAL = new HashSet<TCONDICIONAL>();
            this.TORCAMENTO = new HashSet<TORCAMENTO>();
            this.TPEDIDOVENDA = new HashSet<TPEDIDOVENDA>();
        }
    
        public int CONTROLE { get; set; }
        public string DAV { get; set; }
        public string PREVENDA { get; set; }
        public Nullable<int> RPS { get; set; }
        public Nullable<int> NUMEROOS { get; set; }
        public Nullable<int> NUMEROLOTE { get; set; }
        public Nullable<int> SENHACOMANDA { get; set; }
        public Nullable<int> NUMERONOTAMANUAL { get; set; }
        public Nullable<int> CODIGOCLIENTE { get; set; }
    
        public virtual ICollection<TCONDICIONAL> TCONDICIONAL { get; set; }
        public virtual ICollection<TORCAMENTO> TORCAMENTO { get; set; }
        public virtual ICollection<TPEDIDOVENDA> TPEDIDOVENDA { get; set; }
    }
}
