//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSUBGRUPOESTOQUE
    {
        public TSUBGRUPOESTOQUE()
        {
            this.TESTOQUE = new HashSet<TESTOQUE>();
        }
    
        public int CONTROLE { get; set; }
        public string SUBGRUPO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CODGRUPO { get; set; }
        public string GRUPO { get; set; }
    
        public virtual ICollection<TESTOQUE> TESTOQUE { get; set; }
        public virtual TGRUPOESTOQUE TGRUPOESTOQUE { get; set; }
    }
}
