//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTABELAPRECO
    {
        public TTABELAPRECO()
        {
            this.TESTOQUE = new HashSet<TESTOQUE>();
            this.TITEMTABELAPRECO = new HashSet<TITEMTABELAPRECO>();
            this.TITENSVENDANFE = new HashSet<TITENSVENDANFE>();
        }
    
        public int CONTROLE { get; set; }
        public string NOMETABELA { get; set; }
        public Nullable<System.DateTime> DATAINICIAL { get; set; }
        public Nullable<System.DateTime> DATAFINAL { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string ATIVO { get; set; }
        public decimal PERCDESCONTO { get; set; }
        public decimal PERCACRESCIMO { get; set; }
        public string EXPIRADO { get; set; }
    
        public virtual ICollection<TESTOQUE> TESTOQUE { get; set; }
        public virtual ICollection<TITEMTABELAPRECO> TITEMTABELAPRECO { get; set; }
        public virtual ICollection<TITENSVENDANFE> TITENSVENDANFE { get; set; }
    }
}
