//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTEMPPDV
    {
        public int CONTROLE { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public string CAMPO11 { get; set; }
        public string CAMPO12 { get; set; }
        public string CAMPO13 { get; set; }
        public string CAMPO14 { get; set; }
        public string CAMPO15 { get; set; }
        public Nullable<decimal> CAMPO16 { get; set; }
        public Nullable<decimal> CAMPO17 { get; set; }
        public Nullable<decimal> CAMPO18 { get; set; }
        public Nullable<decimal> CAMPO19 { get; set; }
        public Nullable<decimal> CAMPO20 { get; set; }
    }
}
