//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTEMP3
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CAMPO1 { get; set; }
        public Nullable<int> CAMPO2 { get; set; }
        public Nullable<int> CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public Nullable<decimal> CAMPO7 { get; set; }
        public Nullable<decimal> CAMPO8 { get; set; }
        public Nullable<decimal> CAMPO9 { get; set; }
        public Nullable<decimal> CAMPO10 { get; set; }
    }
}
