//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTEMPCOMPRA
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CAMPO1 { get; set; }
        public Nullable<int> CAMPO2 { get; set; }
        public Nullable<int> CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public Nullable<decimal> CAMPO10 { get; set; }
        public Nullable<decimal> CAMPO11 { get; set; }
        public Nullable<decimal> CAMPO12 { get; set; }
        public Nullable<decimal> CAMPO13 { get; set; }
        public Nullable<decimal> CAMPO14 { get; set; }
        public Nullable<decimal> CAMPO15 { get; set; }
        public string CAMPO16 { get; set; }
        public string CAMPO17 { get; set; }
        public string CAMPO18 { get; set; }
        public string CAMPO19 { get; set; }
        public string CAMPO20 { get; set; }
        public string CAMPO21 { get; set; }
        public string CAMPO22 { get; set; }
        public Nullable<decimal> CAMPO23 { get; set; }
        public Nullable<decimal> CAMPO24 { get; set; }
        public byte[] CAMPO25 { get; set; }
        public Nullable<decimal> CAMPO26 { get; set; }
        public Nullable<decimal> CAMPO27 { get; set; }
        public string CAMPO28 { get; set; }
        public string CAMPO29 { get; set; }
        public Nullable<decimal> CAMPONUMERICO30 { get; set; }
        public Nullable<decimal> CAMPONUMERICO31 { get; set; }
        public Nullable<decimal> CAMPONUMERICO32 { get; set; }
        public Nullable<decimal> CAMPONUMERICO33 { get; set; }
        public Nullable<decimal> CAMPONUMERICO34 { get; set; }
        public Nullable<decimal> CAMPONUMERICO35 { get; set; }
        public string CAMPO30 { get; set; }
        public string CAMPO31 { get; set; }
        public string CAMPO32 { get; set; }
    }
}
