//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTEMPCAIXA
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CAMPO1 { get; set; }
        public Nullable<int> CAMPO2 { get; set; }
        public Nullable<int> CAMPO3 { get; set; }
        public Nullable<int> CAMPO4 { get; set; }
        public Nullable<int> CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public Nullable<decimal> CAMPO11 { get; set; }
        public Nullable<decimal> CAMPO12 { get; set; }
        public Nullable<decimal> CAMPO13 { get; set; }
        public Nullable<decimal> CAMPO14 { get; set; }
        public Nullable<decimal> CAMPO15 { get; set; }
    }
}
