//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTEMPM
    {
        public int CONTROLE { get; set; }
        public string GM1 { get; set; }
        public string GM2 { get; set; }
        public string GM3 { get; set; }
        public string GM4 { get; set; }
        public string GM5 { get; set; }
        public string GM6 { get; set; }
        public string GM7 { get; set; }
        public string GM8 { get; set; }
        public string GM9 { get; set; }
        public string GM10 { get; set; }
        public decimal VGM1 { get; set; }
        public decimal VGM2 { get; set; }
        public decimal VGM3 { get; set; }
        public decimal VGM4 { get; set; }
        public decimal VGM5 { get; set; }
        public decimal VGM6 { get; set; }
        public decimal VGM7 { get; set; }
        public decimal VGM8 { get; set; }
        public decimal VGM9 { get; set; }
        public decimal VGM10 { get; set; }
    }
}
