//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO
    {
        public TUSUARIO()
        {
            this.TCONTROLEMODULO = new HashSet<TCONTROLEMODULO>();
        }
    
        public int CONTROLE { get; set; }
        public int CODFUNCIONARIO { get; set; }
        public string FUNCIONARIONOME { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string NIVELACESSO { get; set; }
        public string CLIENTE { get; set; }
        public string VENDA { get; set; }
        public string RECEBER { get; set; }
        public string ORCAMENTO { get; set; }
        public string ESTOQUE { get; set; }
        public string PAGAR { get; set; }
        public string CAIXA { get; set; }
        public string BANCO { get; set; }
        public string PEDIDOCOMPRA { get; set; }
        public string COMPRA { get; set; }
        public string FORNECEDOR { get; set; }
        public string PEDIDOVENDA { get; set; }
        public string FUNCIONARIO { get; set; }
        public string EMITENTE { get; set; }
        public string BACKUP { get; set; }
        public string CONFIGURACAO { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public Nullable<int> CODCENTROCUSTO { get; set; }
        public string CENTROCUSTO { get; set; }
        public string VENDAPDV { get; set; }
        public string ORDEMSERVICO { get; set; }
        public string USUARIO { get; set; }
        public string TRANSPORTADORA { get; set; }
        public string ESPECIE { get; set; }
        public string CONVENIO { get; set; }
        public string NFCE { get; set; }
        public string COMANDA { get; set; }
        public string CONFIGURACAONFCE { get; set; }
        public string NOTAMANUAL { get; set; }
        public string AGENDA { get; set; }
        public string CONFIGURACAOCOMANDA { get; set; }
        public string RELATORIOSFINANCEIRO { get; set; }
        public string VALORESCOMANDAS { get; set; }
        public string VALORESRECEBER { get; set; }
    
        public virtual TCENTROCUSTO TCENTROCUSTO { get; set; }
        public virtual ICollection<TCONTROLEMODULO> TCONTROLEMODULO { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
    }
}
