//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVALIDADEESTOQUE
    {
        public TVALIDADEESTOQUE()
        {
            this.TITEMNFEVALIDADEESTOQUE = new HashSet<TITEMNFEVALIDADEESTOQUE>();
        }
    
        public int CONTROLE { get; set; }
        public int CODPRODUTO { get; set; }
        public string PRODUTO { get; set; }
        public string LOTE { get; set; }
        public System.DateTime DATAVALIDADE { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public string TERMINOUESTOQUE { get; set; }
        public Nullable<System.DateTime> DATAFABRICACAO { get; set; }
        public Nullable<decimal> QTDE { get; set; }
    
        public virtual ICollection<TITEMNFEVALIDADEESTOQUE> TITEMNFEVALIDADEESTOQUE { get; set; }
    }
}
