//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVENDANFE
    {
        public TVENDANFE()
        {
            this.TENTREGANFE = new HashSet<TENTREGANFE>();
            this.TITEMNFEVEICULO = new HashSet<TITEMNFEVEICULO>();
            this.TITENNFEGRADE = new HashSet<TITENNFEGRADE>();
            this.TITENNFESERIAL = new HashSet<TITENNFESERIAL>();
            this.TITENSVENDANFE = new HashSet<TITENSVENDANFE>();
            this.TPAGAR = new HashSet<TPAGAR>();
        }
    
        public int CONTROLE { get; set; }
        public string NATUREZAOPERACAO { get; set; }
        public string NUMERONOTA { get; set; }
        public string SERIE { get; set; }
        public Nullable<System.DateTime> DATAEMISSAO { get; set; }
        public Nullable<System.DateTime> DATASAIDAEMTRADA { get; set; }
        public string TIPOOPERACAO { get; set; }
        public string CODIGOMUNICIPIO { get; set; }
        public string CHAVEACESSO { get; set; }
        public string CNPJDESTINATARIO { get; set; }
        public string CPFDESTINATARIO { get; set; }
        public string RAZAOSOCIALDESTINATARIO { get; set; }
        public string ENDERECODESTINATARIO { get; set; }
        public string NUMERODESTINATARIO { get; set; }
        public string BAIRRODESTINATARIO { get; set; }
        public Nullable<int> CODCIDADEDESTINATARIO { get; set; }
        public string CIDADEDESTINATARIO { get; set; }
        public string UFDESTINATARIO { get; set; }
        public string IEDESTINATARIO { get; set; }
        public string CEPDESTINATARIO { get; set; }
        public string PAISDESTINATARIO { get; set; }
        public string TELEFONEDESTINATARIO { get; set; }
        public Nullable<decimal> BASECALCULOICMS { get; set; }
        public Nullable<decimal> VALORTOTALICMS { get; set; }
        public Nullable<decimal> BASECALCULOICMSST { get; set; }
        public Nullable<decimal> VALORTOTALICMSST { get; set; }
        public Nullable<decimal> VALORTOTALFRETE { get; set; }
        public Nullable<decimal> VALORTOTALSEGURO { get; set; }
        public Nullable<decimal> VALORTOTALDESCONTO { get; set; }
        public Nullable<decimal> VALORTOTALIPI { get; set; }
        public Nullable<decimal> VALORTOTALPIS { get; set; }
        public Nullable<decimal> VALORTOTALCOFINS { get; set; }
        public Nullable<decimal> OUTRASDESPESAS { get; set; }
        public Nullable<decimal> VALORTOTALNFE { get; set; }
        public string CNPJTRANSPORTADORA { get; set; }
        public string CPFTRANSPORTADORA { get; set; }
        public string ANTTTRANSPORTADORA { get; set; }
        public string PLACATRANSPORTADORA { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public Nullable<int> CODTRANSPORTADORA { get; set; }
        public Nullable<decimal> TOTALPRODUTOS { get; set; }
        public string UFTRANSPORTADORA { get; set; }
        public Nullable<decimal> QUANTIDADE { get; set; }
        public string ESPECIE { get; set; }
        public string MARCA { get; set; }
        public string NUMERACAO { get; set; }
        public Nullable<decimal> PESOLIQUIDO { get; set; }
        public Nullable<decimal> PESOBRUTO { get; set; }
        public string ENDERECOTRANSPORTADORA { get; set; }
        public string CIDADETRANSPORTADORA { get; set; }
        public string IETRANSPORTADORA { get; set; }
        public string INFORMACOESCOMPLEMENTARES { get; set; }
        public string INFORMACOESFISCO { get; set; }
        public string MODOFRETE { get; set; }
        public string RAZAOSOCIALTRANSPORTADORA { get; set; }
        public string MODELO { get; set; }
        public string CANCELADA { get; set; }
        public System.DateTime DATACADASTRO { get; set; }
        public System.TimeSpan HORACADASTRO { get; set; }
        public Nullable<int> CODOPERACAO { get; set; }
        public string TIPOEMISSAO { get; set; }
        public string FINALIDADEEMISSAO { get; set; }
        public string FORMATOIMPRESSAO { get; set; }
        public string IDENTIFICACAOAMBIENTE { get; set; }
        public string PROTOCOLO { get; set; }
        public string CPFEMITENTE { get; set; }
        public Nullable<System.TimeSpan> HORAENTRADASAIDA { get; set; }
        public string EMAILDESTINATARIO { get; set; }
        public string STATUS { get; set; }
        public string FATURADUPLICATA { get; set; }
        public string INUTILIZADA { get; set; }
        public string CONTINGENCIA { get; set; }
        public string INDICADORPAGAMENTO { get; set; }
        public Nullable<int> CODFUNCIONARIO { get; set; }
        public string FUNCIONARIO { get; set; }
        public Nullable<decimal> VALORENTRADA { get; set; }
        public Nullable<decimal> VALORDESCONTOITEM { get; set; }
        public Nullable<int> NOTA { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> VALORIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> TOTALCUSTOPRODUTO { get; set; }
        public Nullable<decimal> TOTALSERVICO { get; set; }
        public Nullable<decimal> TOTALISS { get; set; }
        public Nullable<decimal> VALORTOTALBCSERVICO { get; set; }
        public string JUSTIFICATIVA { get; set; }
        public string STATUSDEENVIO { get; set; }
        public string PROTOCOLOCANCELAMENTO { get; set; }
        public string CODIGOSTATUSCANCELAMENTO { get; set; }
        public Nullable<System.DateTime> DATAEHORACANCELAMENTO { get; set; }
        public string MOTIVOCANCELAMENTO { get; set; }
        public Nullable<int> SEQUENCIACCE { get; set; }
        public string AVISTA { get; set; }
        public Nullable<int> CODOS { get; set; }
        public Nullable<int> CODORCAMENTO { get; set; }
        public Nullable<int> CODPRODUTO { get; set; }
        public string FINALIDADEOPERACAO { get; set; }
        public string CHECADO { get; set; }
        public Nullable<int> CODCONDICIONAL { get; set; }
        public string JAFATURADA { get; set; }
        public string UFEMBARQUE { get; set; }
        public string LOCALEMBARQUE { get; set; }
        public Nullable<int> CODFORNECEDOR { get; set; }
        public Nullable<int> CODCCFECF { get; set; }
        public Nullable<decimal> VALORICMSUFDEST { get; set; }
        public Nullable<decimal> VALORICMSUFREMET { get; set; }
        public string TIPODEVENDA { get; set; }
        public Nullable<int> CODPEDIDOVENDA { get; set; }
        public string ESPECIEPAGAMENTO { get; set; }
        public string INFORMACAOFISCAL { get; set; }
        public string IDESTRANGEIRO { get; set; }
        public Nullable<int> CODVENDEDOR { get; set; }
        public string VENDEDOR { get; set; }
    
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual ICollection<TENTREGANFE> TENTREGANFE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual ICollection<TITEMNFEVEICULO> TITEMNFEVEICULO { get; set; }
        public virtual ICollection<TITENNFEGRADE> TITENNFEGRADE { get; set; }
        public virtual ICollection<TITENNFESERIAL> TITENNFESERIAL { get; set; }
        public virtual ICollection<TITENSVENDANFE> TITENSVENDANFE { get; set; }
        public virtual TOPERACAO TOPERACAO { get; set; }
        public virtual ICollection<TPAGAR> TPAGAR { get; set; }
        public virtual TTRANSPORTADORA TTRANSPORTADORA { get; set; }
    }
}
