//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVENDAECF
    {
        public TVENDAECF()
        {
            this.TITEMECFGRADE = new HashSet<TITEMECFGRADE>();
            this.TITEMECFSERIAL = new HashSet<TITEMECFSERIAL>();
            this.TITEMVENDAECF = new HashSet<TITEMVENDAECF>();
            this.TPAGAMENTOVENDAECF = new HashSet<TPAGAMENTOVENDAECF>();
        }
    
        public int CONTROLE { get; set; }
        public string COOECF { get; set; }
        public System.DateTime DATAHORACADASTRO { get; set; }
        public System.DateTime DATAEMISSAOECF { get; set; }
        public System.TimeSpan HORAEMISSAOECF { get; set; }
        public Nullable<int> CODCLIENTE { get; set; }
        public string CLIENTE { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string CNPJ { get; set; }
        public string IE { get; set; }
        public string IM { get; set; }
        public string ENDERECO { get; set; }
        public string COMPLEMENTO { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string CIDADE { get; set; }
        public string UF { get; set; }
        public string CEP { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public Nullable<int> CODVENDEDOR { get; set; }
        public string VENDEDOR { get; set; }
        public string OBS { get; set; }
        public Nullable<decimal> PERCDESCONTO { get; set; }
        public Nullable<decimal> PERCACRESCIMO { get; set; }
        public Nullable<decimal> VALORDESCONTO { get; set; }
        public Nullable<decimal> VALORACRESCIMO { get; set; }
        public Nullable<decimal> TOTALBRUTO { get; set; }
        public Nullable<decimal> TOTALLIQUIDO { get; set; }
        public Nullable<decimal> VALORICMS { get; set; }
        public string SITUACAO { get; set; }
        public string NUMEROSERIEECF { get; set; }
        public Nullable<decimal> TOTALDESCONTOITEM { get; set; }
        public Nullable<decimal> TOTALACRESCIMOITEM { get; set; }
        public Nullable<int> QTDEITEM { get; set; }
        public Nullable<int> CODCANCELAMENTOVENDA { get; set; }
        public string MOTIVOCANCELAMENTOVENDA { get; set; }
        public Nullable<decimal> VALORPAGODINHEIRO { get; set; }
        public Nullable<decimal> VALORPAGOCARTAO { get; set; }
        public Nullable<decimal> VALORPAGOCHEQUE { get; set; }
        public Nullable<decimal> VALORPAGOCONVENIO { get; set; }
        public Nullable<decimal> VALORPAGOVALE { get; set; }
        public Nullable<decimal> VALORPAGOCREDIARIO { get; set; }
        public Nullable<decimal> TROCO { get; set; }
        public Nullable<int> CCF { get; set; }
        public string CANCELADO { get; set; }
        public Nullable<int> CODOPERADOR { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<decimal> LEITURASUBTOTALECF { get; set; }
        public Nullable<int> CRO { get; set; }
        public Nullable<int> NUMEROECF { get; set; }
        public string FINALIZADOOK { get; set; }
        public string MODELOECF { get; set; }
        public string SUBMODELOECF { get; set; }
        public string MD5R04 { get; set; }
        public Nullable<decimal> VALORIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> PERCIMPOSTOMEDIO { get; set; }
        public Nullable<decimal> TOTALCUSTOPRODUTO { get; set; }
        public Nullable<int> CONTROLENOPDV { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> NUMERONF { get; set; }
        public Nullable<decimal> VALORIMPOSTOMEDIOESTADUAL { get; set; }
        public Nullable<decimal> VALORIMPOSTOMEDIOMUNICIPAL { get; set; }
        public string MESCLAR { get; set; }
        public string MESCLADO { get; set; }
    
        public virtual TCIDADE TCIDADE { get; set; }
        public virtual TCLIENTE TCLIENTE { get; set; }
        public virtual TFUNCIONARIO TFUNCIONARIO { get; set; }
        public virtual ICollection<TITEMECFGRADE> TITEMECFGRADE { get; set; }
        public virtual ICollection<TITEMECFSERIAL> TITEMECFSERIAL { get; set; }
        public virtual ICollection<TITEMVENDAECF> TITEMVENDAECF { get; set; }
        public virtual TMOTIVOCANCELAMENTOVENDA TMOTIVOCANCELAMENTOVENDA { get; set; }
        public virtual ICollection<TPAGAMENTOVENDAECF> TPAGAMENTOVENDAECF { get; set; }
    }
}
