//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgbr.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVENDANFEREFERENCIADA
    {
        public int CONTROLE { get; set; }
        public Nullable<int> CODNFE { get; set; }
        public string CNPJ { get; set; }
        public string CODIGOUF { get; set; }
        public string MODELO { get; set; }
        public string SERIE { get; set; }
        public string NUMERONF { get; set; }
        public string IE { get; set; }
        public string NUMEROECF { get; set; }
        public string NUMEROCOO { get; set; }
        public string CPF { get; set; }
        public string CHAVENFE { get; set; }
        public string DESCRICAOMODELO { get; set; }
        public string MESANO { get; set; }
    }
}
