//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIME {
    
    
    public partial class OSAbertura3 {
        
        /// <summary>
        /// ToolkitScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        /// <summary>
        /// Label3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label3;
        
        /// <summary>
        /// labDadosCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labDadosCliente;
        
        /// <summary>
        /// Label4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label4;
        
        /// <summary>
        /// labDadosCAparelho control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labDadosCAparelho;
        
        /// <summary>
        /// Bt_retornar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Bt_retornar;
        
        /// <summary>
        /// CaixaMensagem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Apresentacao.Controles.Mensagem CaixaMensagem1;
        
        /// <summary>
        /// BT_Concluir control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BT_Concluir;
        
        /// <summary>
        /// plnImprimi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.ModalPopupExtender plnImprimi;
        
        /// <summary>
        /// PanelImprimi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel PanelImprimi;
        
        /// <summary>
        /// labFechar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label labFechar;
        
        /// <summary>
        /// cmdFechar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button cmdFechar;
        
        /// <summary>
        /// RBBobina control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RBBobina;
        
        /// <summary>
        /// RBA5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RBA5;
        
        /// <summary>
        /// CBEtiqueta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CBEtiqueta;
        
        /// <summary>
        /// LabQuantidade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label LabQuantidade;
        
        /// <summary>
        /// txtQuantidade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtQuantidade;
        
        /// <summary>
        /// BtImprimir control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button BtImprimir;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SIME.OS_Sime Master {
            get {
                return ((SIME.OS_Sime)(base.Master));
            }
        }
    }
}
