//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIME.Produtos {
    
    
    public partial class UploadFile {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// upXML control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload upXML;
        
        /// <summary>
        /// ler control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Data.
        /// To modify move Data declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ler;
    }
}
